=== alakim/slavbible/trunk/psalter/src/psalm.dtd
<!ELEMENT psalm (title, verse*)>
<!ATTLIST psalm
	nr CDATA #REQUIRED
>
<!ELEMENT verse (#PCDATA | slav | rus)*>
<!ATTLIST verse
	nr CDATA #REQUIRED
>
<!ELEMENT num (#PCDATA)>
<!ELEMENT initial (#PCDATA)>
<!ELEMENT title (#PCDATA | num | rus)*>
<!ELEMENT rus (#PCDATA)>
<!ELEMENT slav (#PCDATA | num | initial)*>

=== alakim/slavbible/trunk/psalter/src/ps_20.xml
<?xml version="1.0" encoding="Windows-1251"?>
<!DOCTYPE psalm SYSTEM "psalm.dtd">
<?xml-stylesheet type="text/xsl" href="Page.xsl"?>
<psalm nr="20">
	<title>
		<num>№</num> Pал0мъ дв7ду, <num>к7</num>.</title>
	<verse nr="1">
		<slav>
			<initial>Г</initial>Dи, си1лою твоeю возвесели1тсz цaрь, и3 њ спcніи твоeмъ возрaдуетсz ѕэлw2.</slav>
		<rus>Господи! силою Твоею веселится царь и о спасении Твоем безмерно радуется.</rus>
	</verse>
	<verse nr="2">
		<slav>
			<num>G</num> Желaніе сeрдца є3гw2 дaлъ є3си2 є3мY, и3 хотёніz ўстнY є3гw2 нёси лиши1лъ є3го2.</slav>
		<rus>Ты дал ему, чего желало сердце его, и прошения уст его не отринул,</rus>
	</verse>
	<verse nr="3">
		<slav>
			<num>д7</num> Ћкw предвари1лъ є3си2 є3го2 блгcвeніемъ бlгостhннымъ, положи1лъ є3си2 на главЁ є3гw2 вэнeцъ t кaмене чeстна.</slav>
		<rus>ибо Ты встретил его благословениями благости, возложил на голову его венец из чистого золота.</rus>
	</verse>
	<verse nr="4">
		<slav>
			<num>є7</num> ЖивотA проси1лъ є4сть ў тебє2, и3 дaлъ є3си2 є3мY долготY днjй во вёкъ вёка.</slav>
		<rus>Он просил у Тебя жизни; Ты дал ему долгоденствие на век и век.</rus>
	</verse>
	<verse nr="5">
		<slav>
			<num>ѕ7</num> Вeліz слaва є3гw2 спcніемъ твои1мъ: слaву и3 велелёпіе возложи1ши на него2.</slav>
		<rus>Велика слава его в спасении Твоем; Ты возложил на него честь и величие.</rus>
	</verse>
	<verse nr="6">
		<slav>
			<num>з7</num> Ћкw дaси є3мY блгcвeніе во вёкъ вёка: возвесели1ши є3гw2 рaдостію съ лицeмъ твои1мъ.</slav>
		<rus>Ты положил на него благословения на веки, возвеселил его радостью лица Твоего,</rus>
	</verse>
	<verse nr="7">
		<slav>
			<num>}</num> Ћкw цaрь ўповaетъ на гDа, и3 млcтію вhшнzгw не подви1житсz.</slav>
		<rus>ибо царь уповает на Господа, и во благости Всевышнего не поколеблется.</rus>
	</verse>
	<verse nr="8">
		<slav>
			<num>f7</num> Да њбрsщетсz рукA твоS всBмъ врагHмъ твои6мъ, десни1ца твоS да њбрsщетъ вс‰ ненави1дzщыz тебE.</slav>
		<rus>Рука Твоя найдет всех врагов Твоих, десница Твоя найдет [всех] ненавидящих Тебя.</rus>
	</verse>
	<verse nr="9">
		<slav>
			<num>‹</num> Ћкw положи1ши и5хъ ћкw пeщь џгненную во врeмz лицA твоегw2: гDь гнёвомъ свои1мъ смzтeтъ |, и3 снёсть и5хъ џгнь.</slav>
		<rus>Во время гнева Твоего Ты сделаешь их, как печь огненную; во гневе Своем Господь погубит их, и пожрет их огонь.</rus>
	</verse>
	<verse nr="10">
		<slav>
			<num>№i</num> Пл0дъ и4хъ t земли2 погуби1ши, и3 сёмz и4хъ t сынHвъ человёческихъ.</slav>
		<rus>Ты истребишь плод их с земли и семя их - из среды сынов человеческих,</rus>
	</verse>
	<verse nr="11">
		<slav>
			<num>в7i</num> Ћкw ўклони1ша на тS ѕл†z, помhслиша совёты, и5хже не возм0гутъ состaвити.</slav>
		<rus>ибо они предприняли против Тебя злое, составили замыслы, но не могли [выполнить их].</rus>
	</verse>
	<verse nr="12">
		<slav>
			<num>Gi</num> Ћкw положи1ши | хребeтъ: во и3збhтцэхъ твои1хъ ўгот0виши лицE и4хъ.</slav>
		<rus>Ты поставишь их целью, из луков Твоих пустишь стрелы в лице их.</rus>
	</verse>
	<verse nr="13">
		<slav>
			<num>д7i</num> Вознеси1сz, гDи, си1лою твоeю: воспоeмъ и3 поeмъ си6лы тво‰.</slav>
		<rus>>Вознесись, Господи, силою Твоею: мы будем воспевать и прославлять Твое могущество.</rus>
	</verse>
</psalm>

=== alakim/slavbible/psalter/src/ps_56.xml
<?xml version="1.0" encoding="Windows-1251"?>
<!DOCTYPE psalm SYSTEM "psalm.dtd">
<?xml-stylesheet type="text/xsl" href="Page.xsl"?>
<psalm nr="56">
	<title>
		<num>№</num> Въ конeцъ, да не растли1ши, дв7ду въ столпописaніе, внегдA є3мY tбэгaти t лицA саyлова въ пещeру, <num>н7ѕ</num>.</title>
	<verse nr="1">
		<slav>
			<initial>П</initial>оми1луй мS, б9е, поми1луй мS: ћкw на тS ўповA душA моS, и3 на сёнь крилу3 твоє1ю надёюсz, д0ндеже прeйдетъ беззак0ніе.</slav>
		<rus>Помилуй меня, Боже, помилуй меня, ибо на Тебя уповает душа моя, и в тени крыл Твоих я укроюсь, доколе не пройдут беды.</rus>
	</verse>
	<verse nr="2">
		<slav>
			<num>G</num> ВоззовY къ бGу вhшнему, бGу бlгодёzвшему мнЁ.</slav>
		<rus>Воззову к Богу Всевышнему, Богу, благодетельствующему мне;</rus>
	</verse>
	<verse nr="3">
		<slav>
			<num>д7</num> ПослA съ нб7сE и3 сп7сe мz, дадE въ поношeніе попирaющыz мS: послA бGъ млcть свою2 и3 и4стину свою2,</slav>
		<rus>Он пошлет с небес и спасет меня; посрамит ищущего поглотить меня; пошлет Бог милость Свою и истину Свою.</rus>
	</verse>
	<verse nr="4">
		<slav>
			<num>є7</num> и3 и3збaви дyшу мою2 t среды2 скЂмнwвъ. Поспaхъ смущeнъ: сhнове человёчестіи, зyбы и4хъ nр{жіz и3 стрёлы, и3 z3зhкъ и4хъ мeчь џстръ. </slav>
		<rus>Душа моя среди львов; я лежу среди дышущих пламенем, среди сынов человеческих, у которых зубы - копья и стрелы, и у которых язык - острый меч.</rus>
	</verse>
	<verse nr="5">
		<slav>
			<num>ѕ7</num> Вознеси1сz на нб7сA, б9е, и3 по всeй земли2 слaва твоS.</slav>
		<rus>Будь превознесен выше небес, Боже, и над всею землею да будет слава Твоя!</rus>
	</verse>
	<verse nr="6">
		<slav>
			<num>з7</num> Сёть ўгот0ваша ногaмъ мои6мъ, и3 слzк0ша дyшу мою2: и3скопaша пред8 лицeмъ мои1мъ ћму, и3 впад0ша въ ню2.</slav>
		<rus>Приготовили сеть ногам моим; душа моя поникла; выкопали предо мною яму, и сами упали в нее.</rus>
	</verse>
	<verse nr="7">
		<slav>
			<num>}</num> Гот0во сeрдце моE, б9е, гот0во сeрдце моE: воспою2  и пою2 во слaвэ моeй.</slav>
		<rus>Готово сердце мое, Боже, готово сердце мое: буду петь и славить.</rus>
	</verse>
	<verse nr="8">
		<slav>
			<num>f7</num> Востaни, слaва моS, востaни, pалти1рю и3 гyсли: востaну рaнw.</slav>
		<rus>Воспрянь, слава моя, воспрянь, псалтирь и гусли! Я встану рано.</rus>
	</verse>
	<verse nr="9">
		<slav>
			<num>‹</num> И#сповёмсz тебЁ въ лю1дехъ, гDи, воспою2 тебЁ во kзhцэхъ:</slav>
		<rus>Буду славить Тебя, Господи, между народами; буду воспевать Тебя среди племен,</rus>
	</verse>
	<verse nr="10">
		<slav>
			<num>№i</num> ћкw возвели1чисz до нб7съ млcть твоS и3 дaже до w4блакъ и4стина твоS.</slav>
		<rus>ибо до небес велика милость Твоя и до облаков истина Твоя.</rus>
	</verse>
	<verse nr="11">
		<slav>
			<num>в7i</num> Вознеси1сz на нб7сA, б9е, и3 по всeй земли2 слaва твоS.</slav>
		<rus>Будь превознесен выше небес, Боже, и над всею землею да будет слава Твоя!</rus>
	</verse>
</psalm>

=== alakim/slavbible/psalter/src/ps_52.xml
<?xml version="1.0" encoding="Windows-1251"?>
<!DOCTYPE psalm SYSTEM "psalm.dtd">
<?xml-stylesheet type="text/xsl" href="Page.xsl"?>
<psalm nr="52">
	<title>
		<num>№</num> Въ конeцъ, њ маелefэ, рaзума дв7ду, <num>н7в</num>.</title>
	<verse nr="1">
		<slav>
			<initial>Р</initial>ечE безyменъ въ сeрдцы своeмъ: нёсть бGъ. Растлёша и3 њмерзи1шасz въ беззак0ніихъ, нёсть творsй бlг0е.</slav>
		<rus>Сказал безумец в сердце своем: "нет Бога". Развратились они и совершили гнусные преступления; нет делающего добро.</rus>
	</verse>
	<verse nr="2">
		<slav>
			<num>G</num> БGъ съ нб7сE прини1че на сhны человёчєскіz, ви1дэти, ѓще є4сть разумэвazй и3ли2 взыскazй бGа.</slav>
		<rus>Бог с небес призрел на сынов человеческих, чтобы видеть, есть ли разумеющий, ищущий Бога.</rus>
	</verse>
	<verse nr="3">
		<slav>
			<num>д7</num> Вси2 ўклони1шасz, вкyпэ непотрeбни бhша: нёсть творsй бlг0е, нёсть до є3ди1нагw.</slav>
		<rus>Все уклонились, сделались равно непотребными; нет делающего добро, нет ни одного.</rus>
	</verse>
	<verse nr="4">
		<slav>
			<num>є7</num> Ни ли2 ўразумёютъ вси2 дёлающіи беззак0ніе, снэдaющіи лю1ди мо‰ въ снёдь хлёба; гDа не призвaша.</slav>
		<rus>Неужели не вразумятся делающие беззаконие, съедающие народ мой, как едят хлеб, и не призывающие Бога?</rus>
	</verse>
	<verse nr="5">
		<slav>
			<num>ѕ7</num> Тaмw ўстраши1шасz стрaха, и3дёже не бЁ стрaхъ: ћкw бGъ разсhпа кHсти человэкоуг0дникwвъ: постыдёшасz, ћкw бGъ ўничижи2 и5хъ.</slav>
		<rus>Там убоятся они страха, где нет страха, ибо рассыплет Бог кости ополчающихся против тебя. Ты постыдишь их, потому что Бог отверг их.</rus>
	</verse>
	<verse nr="6">
		<slav>
			<num>з7</num> Кто2 дaстъ t сіHна сп7сeніе ї}лево; внегдA возврати1тъ бGъ плэнeніе людjй свои1хъ, возрaдуетсz їaкwвъ и3 возвесели1тсz ї}ль.</slav>
		<rus>Кто даст с Сиона спасение Израилю! Когда Бог возвратит пленение народа Своего, тогда возрадуется Иаков и возвеселится Израиль.</rus>
	</verse>
</psalm>

=== alakim/slavbible/psalter/src/ps_67.xml
<?xml version="1.0" encoding="Windows-1251"?>
<!DOCTYPE psalm SYSTEM "psalm.dtd">
<?xml-stylesheet type="text/xsl" href="Page.xsl"?>
<psalm nr="67">
	<title>
		<num>№</num> Въ конeцъ, pал0мъ пёсни дв7ду, <num>…з</num>.</title>
	<verse nr="1">
		<slav>
			<initial>Д</initial>а воскрcнетъ бGъ, и3 расточaтсz врази2 є3гw2, и3 да бэжaтъ t лицA є3гw2 ненави1дzщіи є3го2.</slav>
		<rus>Да восстанет Бог, и расточатся враги Его, и да бегут от лица Его ненавидящие Его.</rus>
	</verse>
	<verse nr="2">
		<slav>
			<num>G</num> Ћкw и3зчезaетъ дhмъ, да и3зчeзнутъ: ћкw тaетъ в0скъ t лицA nгнS, тaкw да поги1бнутъ грBшницы t лицA б9іz:</slav>
		<rus>Как рассеивается дым, Ты рассей их; как тает воск от огня, так нечестивые да погибнут от лица Божия.</rus>
	</verse>
	<verse nr="3">
		<slav>
			<num>д7</num> ґ првdницы да возвеселsтсz, да возрaдуютсz пред8 бGомъ, да насладsтсz въ весeліи.</slav>
		<rus>А праведники да возвеселятся, да возрадуются пред Богом и восторжествуют в радости.</rus>
	</verse>
	<verse nr="4">
		<slav>
			<num>є7</num> Восп0йте бGу, п0йте и4мени є3гw2: путесотвори1те возшeдшему на зaпады, гDь и4мz є3мY: и3 рaдуйтесz пред8 ни1мъ.</slav>
		<rus>Пойте Богу нашему, пойте имени Его, превозносите Шествующего на небесах; имя Ему: Господь, и радуйтесь пред лицем Его.</rus>
	</verse>
	<verse nr="5">
		<slav>
			<num>ѕ7</num> Да смzтyтсz t лицA є3гw2, nц7A си1рыхъ и3 судіи2 вдови1цъ: бGъ въ мёстэ с™ёмъ своeмъ.</slav>
		<rus>Отец сирот и судья вдов Бог во святом Своем жилище.</rus>
	</verse>
	<verse nr="6">
		<slav>
			<num>з7</num> БGъ вселsетъ є3диномhслєнныz въ д0мъ, и3зводS њков†нныz мyжествомъ, тaкожде преwгорчевaющыz живyщыz во гробёхъ.</slav>
		<rus>Бог одиноких вводит в дом, освобождает узников от оков, а непокорные остаются в знойной пустыне.</rus>
	</verse>
	<verse nr="7">
		<slav>
			<num>}</num> Б9е, внегдA и3сходи1ти тебЁ пред8 людьми2 твои1ми, внегдA мимоходи1ти тебЁ въ пустhни,</slav>
		<rus>Боже! когда Ты выходил пред народом Твоим, когда Ты шествовал пустынею,</rus>
	</verse>
	<verse nr="8">
		<slav>
			<num>f7</num> землS потрzсeсz, и4бо небесA кaнуша t лицA бGа сінaина, t лицA бGа ї}лева.</slav>
		<rus>земля тряслась, даже небеса таяли от лица Божия, и этот Синай - от лица Бога, Бога Израилева.</rus>
	</verse>
	<verse nr="9">
		<slav>
			<num>‹</num> Д0ждь в0ленъ tлучи1ши, б9е, достоsнію твоемY, и3 и3знем0же, тh же соверши1лъ є3си2 є5.</slav>
		<rus>Обильный дождь проливал Ты, Боже, на наследие Твое, и когда оно изнемогало от труда, Ты подкреплял его.</rus>
	</verse>
	<verse nr="10">
		<slav>
			<num>№i</num> ЖивHтнаz тво‰ живyтъ на нeй: ўгот0валъ є3си2 бlгостію твоeю ни1щему, б9е.</slav>
		<rus>Народ Твой обитал там; по благости Твоей, Боже, Ты готовил необходимое для бедного.</rus>
	</verse>
	<verse nr="11">
		<slav>
			<num>в7i</num> ГDь дaстъ глаг0лъ благовэствyющымъ си1лою мн0гою:</slav>
		<rus>Господь даст слово: провозвестниц великое множество.</rus>
	</verse>
	<verse nr="12">
		<slav>
			<num>Gi</num> цRь си1лъ возлю1бленнагw, красот0ю (рaди красоты2) д0му раздэли1ти кwрhсти.</slav>
		<rus>Цари воинств бегут, бегут, а сидящая дома делит добычу.</rus>
	</verse>
	<verse nr="13">
		<slav>
			<num>д7i</num> Ѓще поспитE посредЁ предBлъ, крилB голуби6нэ посрeбрєнэ, и3 междор†міz є3S въ блещaніи злaта:</slav>
		<rus>Расположившись в уделах [своих], вы стали, как голубица, которой крылья покрыты серебром, а перья чистым золотом:</rus>
	</verse>
	<verse nr="14">
		<slav>
			<num>є7i</num> внегдA рaзнствитъ нбcный цари6 на нeй, њснэжaтсz въ селмHнэ.</slav>
		<rus>когда Всемогущий рассеял царей на сей земле, она забелела, как снег на Селмоне.</rus>
	</verse>
	<verse nr="15">
		<slav>
			<num>ѕ7i</num> ГорA б9іz, горA тyчнаz, горA ўсырeннаz, горA тyчнаz.</slav>
		<rus>Гора Божия - гора Васанская! гора высокая - гора Васанская!</rus>
	</verse>
	<verse nr="16">
		<slav>
			<num>з7i</num> Вскyю непщyете, г0ры ўсырє1нныz; горA, ю4же бlговоли2 бGъ жи1ти въ нeй: и4бо гDь всели1тсz до концA.</slav>
		<rus>что вы завистливо смотрите, горы высокие, на гору, на которой Бог благоволит обитать и будет Господь обитать вечно?</rus>
	</verse>
	<verse nr="17">
		<slav>
			<num>}i</num> Колесни1ца б9іz тмaми тeмъ, тhсzща гобзyющихъ: гDь въ ни1хъ въ сінaи во с™ёмъ.</slav>
		<rus>Колесниц Божиих тьмы, тысячи тысяч; среди их Господь на Синае, во святилище.</rus>
	</verse>
	<verse nr="18">
		<slav>
			<num>f7i</num> Возшeлъ є3си2 на высотY, плэни1лъ є3си2 плёнъ: пріsлъ є3си2 да‰ніz въ человёцэхъ, и4бо не покарsющыzсz, є4же всели1тисz.</slav>
		<rus>Ты восшел на высоту, пленил плен, принял дары для человеков, так чтоб и из противящихся могли обитать у Господа Бога.</rus>
	</verse>
	<verse nr="19">
		<slav>
			<num>к7</num> ГDь бGъ бlгcвeнъ, бlгcвeнъ гDь дeнь днE: поспэши1тъ нaмъ бGъ спcній нaшихъ.</slav>
		<rus>Благословен Господь всякий день. Бог возлагает на нас бремя, но Он же и спасает нас.</rus>
	</verse>
	<verse nr="20">
		<slav>
			<num>к7а</num> БGъ нaшъ бGъ є4же сп7сaти: и3 гDнz, гDнz и3схHдища смє1ртнаz.</slav>
		<rus>Бог для нас - Бог во спасение; во власти Господа Вседержителя врата смерти.</rus>
	</verse>
	<verse nr="21">
		<slav>
			<num>к7в</num> Nбaче бGъ сокруши1тъ главы6 врагHвъ свои1хъ, вeрхъ вл†съ преходsщихъ въ прегрэшeніихъ свои1хъ.</slav>
		<rus>Но Бог сокрушит голову врагов Своих, волосатое темя закоснелого в своих беззакониях.</rus>
	</verse>
	<verse nr="22">
		<slav>
			<num>к7г</num> РечE гDь: t васaна њбращY, њбращY во глубинaхъ морски1хъ:</slav>
		<rus>Господь сказал: [от Васана возвращу, выведу из глубины морской,</rus>
	</verse>
	<verse nr="23">
		<slav>
			<num>к7д</num> ћкw да њм0читсz ногA твоS въ кр0ви, z3зhкъ пє1съ твои1хъ t вр†гъ t негw2.</slav>
		<rus>чтобы ты погрузил ногу твою, как и псы твои язык свой, в крови врагов].</rus>
	</verse>
	<verse nr="24">
		<slav>
			<num>к7є</num> Ви6дэна бhша шє1ствіz тво‰, б9е, шє1ствіz бGа моегw2 цRS, и4же во с™ёмъ.</slav>
		<rus>Видели шествие Твое, Боже, шествие Бога моего, Царя моего во святыне:</rus>
	</verse>
	<verse nr="25">
		<slav>
			<num>к7ѕ</num> Предвари1ша кн‰зи бли1з8 пою1щихъ, посредЁ дёвъ тmмпaнницъ.</slav>
		<rus>впереди шли поющие, позади играющие на орудиях, в средине девы с тимпанами:</rus>
	</verse>
	<verse nr="26">
		<slav>
			<num>к7з</num> Въ цRквахъ благослови1те бGа, гDа t и3стHчникъ ї}левыхъ.</slav>
		<rus>"в собраниях благословите Бога Господа, вы - от семени Израилева!"</rus>
	</verse>
	<verse nr="27">
		<slav>
			<num>к7и</num> Тaмw веніамjнъ ю3нёйшій во ќжасэ, кн‰зи їyдовы владhки и4хъ, кн‰зи завулw6ни, кнsзи нефfал‡мли. </slav>
		<rus>Там Вениамин младший - князь их; князья Иудины - владыки их, князья Завулоновы, князья Неффалимовы.</rus>
	</verse>
	<verse nr="28">
		<slav>
			<num>к7f</num> Заповёждь, б9е, си1лою твоeю: ўкрэпи2, б9е, сіE, є4же содёлалъ є3си2 въ нaсъ.</slav>
		<rus>Бог твой предназначил тебе силу. Утверди, Боже, то, что Ты соделал для нас!</rus>
	</verse>
	<verse nr="29">
		<slav>
			<num>l</num> T хрaма твоегw2 во їерcли1мъ тебЁ принесyтъ цaріе дaры.</slav>
		<rus>Ради храма Твоего в Иерусалиме цари принесут Тебе дары.</rus>
	</verse>
	<verse nr="30">
		<slav>
			<num>lа</num> Запрети2 ѕвэрє1мъ трHстнымъ: с0нмъ ю3нє1цъ въ ю4ницахъ людски1хъ, є4же затвори1ти и3скушє1нныz сребр0мъ: расточи2 kзhки хотsщыz брaнемъ.</slav>
		<rus>Укроти зверя в тростнике, стадо волов среди тельцов народов, хвалящихся слитками серебра; рассыпь народы, желающие браней.</rus>
	</verse>
	<verse nr="31">
		<slav>
			<num>lв</num> Пріи1дутъ моли6твенницы t є3гЂпта: є3fі0піа предвари1тъ рyку свою2 къ бGу.</slav>
		<rus>Придут вельможи из Египта; Ефиопия прострет руки свои к Богу.</rus>
	</verse>
	<verse nr="32">
		<slav>
			<num>lг</num> Ц†рства земн†z, п0йте бGу, восп0йте гDеви,</slav>
		<rus>Царства земные! пойте Богу, воспевайте Господа,</rus>
	</verse>
	<verse nr="33">
		<slav>
			<num>lд</num> возшeдшему на нб7о нб7сE на вост0ки: сE, дaстъ глaсу своемY глaсъ си1лы.</slav>
		<rus>шествующего на небесах небес от века. Вот, Он дает гласу Своему глас силы.</rus>
	</verse>
	<verse nr="34">
		<slav>
			<num>lє</num> Дади1те слaву бGови: на ї}ли велелёпота є3гw2, и3 си1ла є3гw2 на w4блацэхъ.</slav>
		<rus>Воздайте славу Богу! величие Его - над Израилем, и могущество Его - на облаках.</rus>
	</verse>
	<verse nr="35">
		<slav>
			<num>lѕ</num> Ди1венъ бGъ во с™hхъ свои1хъ: бGъ ї}левъ, т0й дaстъ си1лу и3 держaву лю1демъ свои6мъ. Бlгcвeнъ бGъ.</slav>
		<rus>Страшен Ты, Боже, во святилище Твоем. Бог Израилев - Он дает силу и крепость народу [Своему]. Благословен Бог!</rus>
	</verse>
</psalm>

=== alakim/slavbible/trunk/psalter/src/ps_131.xml
<?xml version="1.0" encoding="Windows-1251"?>
<!DOCTYPE psalm SYSTEM "psalm.dtd">
<?xml-stylesheet type="text/xsl" href="Page.xsl"?>
<psalm nr="131">
	<title>Пёснь степeней, <num>рlа</num>.</title>
	<verse nr="1">
		<slav>
			<initial>П</initial>омzни2, гDи, дв7да и3 всю2 кр0тость є3гw2:</slav>
		<rus>Вспомни, Господи, Давида и все сокрушение его:</rus>
	</verse>
	<verse nr="2">
		<slav>
			<num>в7</num> ћкw клsтсz гDеви, њбэщaсz бGу їaкwвлю:</slav>
		<rus>как он клялся Господу, давал обет Сильному Иакова:</rus>
	</verse>
	<verse nr="3">
		<slav>
			<num>G</num> ѓще вни1ду въ селeніе д0му моегw2, и3ли2 взhду на џдръ постeли моеS:</slav>
		<rus>"не войду в шатер дома моего, не взойду на ложе мое;</rus>
	</verse>
	<verse nr="4">
		<slav>
			<num>д7</num> ѓще дaмъ с0нъ nчи1ма мои1ма, и3 вёждома мои1ма дремaніе, и3 пок0й скраніaма мои1ма:</slav>
		<rus>не дам сна очам моим и веждам моим - дремания,</rus>
	</verse>
	<verse nr="5">
		<slav>
			<num>є7</num> д0ндеже њбрsщу мёсто гDеви, селeніе бGу їaкwвлю.</slav>
		<rus>доколе не найду места Господу, жилища - Сильному Иакова".</rus>
	</verse>
	<verse nr="6">
		<slav>
			<num>ѕ7</num> СE, слhшахомъ | во є3vфрafэ, њбрэт0хомъ | въ полsхъ дубрaвы:</slav>
		<rus>Вот, мы слышали о нем в Ефрафе, нашли его на полях Иарима.</rus>
	</verse>
	<verse nr="7">
		<slav>
			<num>з7</num> вни1демъ въ селє1ніz є3гw2, поклони1мсz на мёсто, и3дёже стоsстэ н0зэ є3гw2.</slav>
		<rus>Пойдем к жилищу Его, поклонимся подножию ног Его.</rus>
	</verse>
	<verse nr="8">
		<slav>
			<num>}</num> Воскcрни, гDи, въ пок0й тв0й, ты2 и3 ківHтъ с™hни твоеS.</slav>
		<rus>Стань, Господи, на место покоя Твоего, - Ты и ковчег могущества Твоего.</rus>
	</verse>
	<verse nr="9">
		<slav>
			<num>f7</num> Сщ7eнницы твои2 њблекyтсz прaвдою, и3 прпdбніи твои2 возрaдуютсz.</slav>
		<rus>Священники Твои облекутся правдою, и святые Твои возрадуются.</rus>
	</verse>
	<verse nr="10">
		<slav>
			<num>‹</num> Дв7да рaди рабA твоегw2, не tврати2 лицE помaзаннагw твоегw2.</slav>
		<rus>Ради Давида, раба Твоего, не отврати лица помазанника Твоего.</rus>
	</verse>
	<verse nr="11">
		<slav>
			<num>№i</num> Клsтсz гDь дв7ду и4стиною, и3 не tвeржетсz є3S: t плодA чрeва твоегw2 посаждY на прест0лэ твоeмъ.</slav>
		<rus>Клялся Господь Давиду в истине, и не отречется ее: "от плода чрева твоего посажу на престоле твоем.</rus>
	</verse>
	<verse nr="12">
		<slav>
			<num>в7i</num> Ѓще сохранsтъ сhнове твои2 завётъ м0й и3 свидBніz мо‰ сі‰, и5мже научY |, и3 сhнове и4хъ до вёка сsдутъ на прест0лэ твоeмъ.</slav>
		<rus>Если сыновья твои будут сохранять завет Мой и откровения Мои, которым Я научу их, то и их сыновья во веки будут сидеть на престоле твоем".</rus>
	</verse>
	<verse nr="13">
		<slav>
			<num>Gi</num> Ћкw и3збрA гDь сіHна, и3зв0ли и5 въ жили1ще себЁ.</slav>
		<rus>Ибо избрал Господь Сион, возжелал [его] в жилище Себе.</rus>
	</verse>
	<verse nr="14">
		<slav>
			<num>д7i</num> Сeй пок0й м0й во вёкъ вёка, здЁ вселю1сz, ћкw и3зв0лихъ и5. </slav>
		<rus>"Это покой Мой на веки: здесь вселюсь, ибо Я возжелал его.</rus>
	</verse>
	<verse nr="15">
		<slav>
			<num>є7i</num> Лови1тву є3гw2 блгcвлszй блгcвлю2, ни1щыz є3гw2 насhщу хлBбы:</slav>
		<rus>Пищу его благословляя благословлю, нищих его насыщу хлебом;</rus>
	</verse>
	<verse nr="16">
		<slav>
			<num>ѕ7i</num> сщ7eнники є3гw2 њблекY во спcніе, и3 прпdбніи є3гw2 рaдостію возрaдуютсz.</slav>
		<rus>священников его облеку во спасение, и святые его радостью возрадуются.</rus>
	</verse>
	<verse nr="17">
		<slav>
			<num>з7i</num> Тaмw возращY р0гъ дв7дови, ўгот0вахъ свэти1лникъ помaзанному моемY.</slav>
		<rus>Там возращу рог Давиду, поставлю светильник помазаннику Моему.</rus>
	</verse>
	<verse nr="18">
		<slav>
			<num>}i</num> Враги2 є3гw2 њблекY студ0мъ, на нeм же процвэтeтъ с™hнz моS.</slav>
		<rus>Врагов его облеку стыдом, а на нем будет сиять венец его".</rus>
	</verse>
</psalm>

=== alakim/slavbible/trunk/psalter/src/ps_102.xml
<?xml version="1.0" encoding="Windows-1251"?>
<!DOCTYPE psalm SYSTEM "psalm.dtd">
<?xml-stylesheet type="text/xsl" href="Page.xsl"?>
<psalm nr="102">
	<title>Pал0мъ дв7ду, <num>Rв</num>.</title>
	<verse nr="1">
		<slav>
			<initial>Б</initial>лагослови2, душE моS, гDа, и3 вс‰ внyтрєннzz мо‰, и4мz с™ое є3гw2: </slav>
		<rus>Благослови, душа моя, Господа, и вся внутренность моя - святое имя Его.</rus>
	</verse>
	<verse nr="2">
		<slav>
			<num>в7</num> благослови2, душE моS, гDа, и3 не забывaй всёхъ воздаsній є3гw2:</slav>
		<rus>Благослови, душа моя, Господа и не забывай всех благодеяний Его.</rus>
	</verse>
	<verse nr="3">
		<slav>
			<num>G</num> њчищaющаго вс‰ беззакHніz тво‰, и3зцэлsющаго вс‰ недyги тво‰,</slav>
		<rus>Он прощает все беззакония твои, исцеляет все недуги твои;</rus>
	</verse>
	<verse nr="4">
		<slav>
			<num>д7</num> и3збавлsющаго t и3стлёніz жив0тъ тв0й, вэнчaющаго тS млcтію и3 щедр0тами,</slav>
		<rus>избавляет от могилы жизнь твою, венчает тебя милостью и щедротами;</rus>
	</verse>
	<verse nr="5">
		<slav>
			<num>є7</num> и3сполнsющаго во бlги1хъ желaніе твоE: њбнови1тсz ћкw џрлz ю4ность твоS.</slav>
		<rus>насыщает благами желание твое: обновляется, подобно орлу, юность твоя.</rus>
	</verse>
	<verse nr="6">
		<slav>
			<num>ѕ7</num> Творsй млcтыни гDь и3 судбY всBмъ њби6димымъ.</slav>
		<rus>Господь творит правду и суд всем обиженным.</rus>
	</verse>
	<verse nr="7">
		<slav>
			<num>з7</num> СказA пути6 сво‰ мwmсeови, сыновHмъ ї}лєвымъ хотBніz сво‰.</slav>
		<rus>Он показал пути Свои Моисею, сынам Израилевым - дела Свои.</rus>
	</verse>
	<verse nr="8">
		<slav>
			<num>}</num> Щeдръ и3 млcтивъ гDь, долготерпэли1въ и3 многомлcтивъ.</slav>
		<rus>Щедр и милостив Господь, долготерпелив и многомилостив:</rus>
	</verse>
	<verse nr="9">
		<slav>
			<num>f7</num> Не до концA прогнёваетсz, нижE во вёкъ враждyетъ:</slav>
		<rus>не до конца гневается, и не вовек негодует.</rus>
	</verse>
	<verse nr="10">
		<slav>
			<num>‹</num> не по беззак0ніємъ нaшымъ сотвори1лъ є4сть нaмъ, нижE по грэхHмъ нaшымъ воздaлъ є4сть нaмъ.</slav>
		<rus>Не по беззакониям нашим сотворил нам, и не по грехам нашим воздал нам:</rus>
	</verse>
	<verse nr="11">
		<slav>
			<num>№i</num> Ћкw по высотЁ небeснэй t земли2, ўтверди1лъ є4сть гDь млcть свою2 на боsщихсz є3гw2:</slav>
		<rus>ибо как высоко небо над землею, так велика милость [Господа] к боящимся Его;</rus>
	</verse>
	<verse nr="12">
		<slav>
			<num>в7i</num> є3ли1кw tстоsтъ вост0цы t з†падъ, ўдaлилъ є4сть t нaсъ беззакHніz н†ша.</slav>
		<rus>как далеко восток от запада, так удалил Он от нас беззакония наши;</rus>
	</verse>
	<verse nr="13">
		<slav>
			<num>Gi</num> Ћкоже щeдритъ nтецъ сhны, ўщeдри гDь боsщихсz є3гw2.</slav>
		<rus>как отец милует сынов, так милует Господь боящихся Его.</rus>
	</verse>
	<verse nr="14">
		<slav>
			<num>д7i</num> Ћкw т0й познA создaніе нaше, помzнY, ћкw пeрсть є3смы2.</slav>
		<rus>Ибо Он знает состав наш, помнит, что мы - персть.</rus>
	</verse>
	<verse nr="15">
		<slav>
			<num>є7i</num> Человёкъ, ћкw травA днjе є3гw2, ћкw цвётъ сeлный, тaкw њцвэтeтъ:</slav>
		<rus>Дни человека - как трава; как цвет полевой, так он цветет.</rus>
	</verse>
	<verse nr="16">
		<slav>
			<num>ѕ7i</num> ћкw дyхъ пр0йде въ нeмъ, и3 не бyдетъ, и3 не познaетъ ктомY мёста своегw2.</slav>
		<rus>Пройдет над ним ветер, и нет его, и место его уже не узнает его.</rus>
	</verse>
	<verse nr="17">
		<slav>
			<num>з7i</num> Млcть же гDнz t вёка и3 до вёка на боsщихсz є3гw2,</slav>
		<rus>Милость же Господня от века и до века к боящимся Его,</rus>
	</verse>
	<verse nr="18">
		<slav>
			<num>}i</num> и3 прaвда є3гw2 на сынёхъ сынHвъ, хранsщихъ завётъ є3гw2 и3 п0мнzщихъ зaпwвэди є3гw2 твори1ти |.</slav>
		<rus>и правда Его на сынах сынов, хранящих завет Его и помнящих заповеди Его, чтобы исполнять их.</rus>
	</verse>
	<verse nr="19">
		<slav>
			<num>f7i</num> ГDь на нб7си2 ўгот0ва прcт0лъ св0й, и3 цrтво є3гw2 всёми њбладaетъ.</slav>
		<rus>Господь на небесах поставил престол Свой, и царство Его всем обладает.</rus>
	</verse>
	<verse nr="20">
		<slav>
			<num>к7</num> Благослови1те гDа, вси2 ѓггли є3гw2, си1льніи крёпостію, творsщіи сл0во є3гw2, ўслhшати глaсъ словeсъ є3гw2.</slav>
		<rus>Благословите Господа, [все] Ангелы Его, крепкие силою, исполняющие слово Его, повинуясь гласу слова Его;</rus>
	</verse>
	<verse nr="21">
		<slav>
			<num>к7а</num> Благослови1те гDа, вс‰ си6лы є3гw2, слуги6 є3гw2, творsщіи в0лю є3гw2.</slav>
		<rus>благословите Господа, все воинства Его, служители Его, исполняющие волю Его;</rus>
	</verse>
</psalm>

=== alakim/slavbible/psalter/src/ps_59.xml
<?xml version="1.0" encoding="Windows-1251"?>
<!DOCTYPE psalm SYSTEM "psalm.dtd">
<?xml-stylesheet type="text/xsl" href="Page.xsl"?>
<psalm nr="59">
	<title>
		<num>№</num> Въ конeцъ, њ и3змэни1тисz хотsщихъ, въ столпописaніе дв7ду, въ научeніе: </title>
	<verse nr="1">
		<slav>
			<num>в7</num> внегдA сожжE средорёчіе сmрjйское и3 сmрjю совaлскую, и3 возврати1сz їwaвъ и3 порази2 є3дHма въ дeбри солeй дванaдесzть тhсzщъ, <num>н7f</num>.</slav>
		<rus>когда он воевал с Сириею Месопотамскою и с Сириею Цованскою, и когда Иоав, возвращаясь, поразил двенадцать тысяч Идумеев в долине Соляной.</rus>
	</verse>
	<verse nr="2">
		<slav>
			<initial>Б</initial>9е, tри1нулъ ны2 є3си2 и3 низложи1лъ є3си2 нaсъ, разгнёвалсz є3си2 и3 ўщeдрилъ є3си2 нaсъ.</slav>
		<rus>Боже! Ты отринул нас, Ты сокрушил нас, Ты прогневался: обратись к нам.</rus>
	</verse>
	<verse nr="3">
		<slav>
			<num>д7</num> Стрsслъ є3си2 зeмлю и3 смути1лъ є3си2 ю5: и3сцэли2 сокрушeніе є3S, ћкw подви1жесz.</slav>
		<rus>Ты потряс землю, разбил ее: исцели повреждения ее, ибо она колеблется.</rus>
	</verse>
	<verse nr="4">
		<slav>
			<num>є7</num> Показaлъ є3си2 лю1демъ твои6мъ жестHкаz: напои1лъ є3си2 нaсъ він0мъ ўмилeніz.</slav>
		<rus>Ты дал испытать народу твоему жестокое, напоил нас вином изумления.</rus>
	</verse>
	<verse nr="5">
		<slav>
			<num>ѕ7</num> Дaлъ є1си2 боsщымсz тебє2 знaменіе, є4же ўбэжaти t лицA лyка.</slav>
		<rus>Даруй боящимся Тебя знамя, чтобы они подняли его ради истины,</rus>
	</verse>
	<verse nr="6">
		<slav>
			<num>з7</num> Ћкw да и3збaвzтсz возлю1бленніи твои2, сп7си2 десни1цею твоeю и3 ўслhши мS.</slav>
		<rus>чтобы избавились возлюбленные Твои; спаси десницею Твоею и услышь меня.</rus>
	</verse>
	<verse nr="7">
		<slav>
			<num>}</num> БGъ возгlа во с™ёмъ своeмъ: возрaдуюсz, и3 раздэлю2 сіки1му, и3 ю3д0ль жили1щъ размёрю.</slav>
		<rus>Бог сказал во святилище Своем: "восторжествую, разделю Сихем и долину Сокхоф размерю:</rus>
	</verse>
	<verse nr="8">
		<slav>
			<num>f7</num> М0й є4сть галаaдъ, и3 м0й є4сть манассjй, є3фрeмъ крёпость главы2 моеS, їyда цaрь м0й.</slav>
		<rus>Мой Галаад, Мой Манассия, Ефрем крепость главы Моей, Иуда скипетр Мой,</rus>
	</verse>
	<verse nr="9">
		<slav>
			<num>‹</num> Мwaвъ кон0бъ ўповaніz моегw2: на їдумeю прострY сап0гъ м0й: мнЁ и3ноплемє1нницы покори1шасz.</slav>
		<rus>Моав умывальная чаша Моя; на Едома простру сапог Мой. Восклицай Мне, земля Филистимская!"</rus>
	</verse>
	<verse nr="10">
		<slav>
			<num>№i</num> Кто2 введeтъ мS во грaдъ њграждeніz; и3ли2 кто2 настaвитъ мS до їдумeи;</slav>
		<rus>Кто введет меня в укрепленный город? Кто доведет меня до Едома?</rus>
	</verse>
	<verse nr="11">
		<slav>
			<num>в7i</num> Не тh ли, б9е, tри1нувый нaсъ; и3 не и3зhдеши, б9е, въ си1лахъ нaшихъ;</slav>
		<rus>Не Ты ли, Боже, Который отринул нас, и не выходишь, Боже, с войсками нашими?</rus>
	</verse>
	<verse nr="12">
		<slav>
			<num>Gi</num> Дaждь нaмъ п0мощь t ск0рби: и3 сyетно спасeніе человёческо.</slav>
		<rus>Подай нам помощь в тесноте, ибо защита человеческая суетна.</rus>
	</verse>
	<verse nr="13">
		<slav>
			<num>д7i</num> Њ бз7э сотвори1мъ си1лу: и3 т0й ўничижи1тъ стужaющыz нaмъ.</slav>
		<rus>С Богом мы окажем силу, Он низложит врагов наших.</rus>
	</verse>
</psalm>
