=== alakim/slavbible/trunk/psalter/src/psalm.dtd
<!ELEMENT psalm (title, verse*)>
<!ATTLIST psalm
	nr CDATA #REQUIRED
>
<!ELEMENT verse (#PCDATA | slav | rus)*>
<!ATTLIST verse
	nr CDATA #REQUIRED
>
<!ELEMENT num (#PCDATA)>
<!ELEMENT initial (#PCDATA)>
<!ELEMENT title (#PCDATA | num | rus)*>
<!ELEMENT rus (#PCDATA)>
<!ELEMENT slav (#PCDATA | num | initial)*>

=== alakim/slavbible/trunk/psalter/src/ps_103.xml
<?xml version="1.0" encoding="Windows-1251"?>
<!DOCTYPE psalm SYSTEM "psalm.dtd">
<?xml-stylesheet type="text/xsl" href="Page.xsl"?>
<psalm nr="103">
	<title>Pал0мъ дв7ду, њ мірстёмъ бытіи2, <num>Rг</num>.</title>
	<verse nr="1">
		<slav>
			<initial>Б</initial>лагослови2, душE моS, гDа. ГDи б9е м0й, возвели1чилсz є3си2 ѕэлw2: во и3сповёданіе и3 въ велелёпоту њблeклсz є3си2:</slav>
		<rus>Благослови, душа моя, Господа! Господи, Боже мой! Ты дивно велик, Ты облечен славою и величием;</rus>
	</verse>
	<verse nr="2">
		<slav>
			<num>в7</num> њдэsйсz свётомъ ћкw ри1зою, простирazй нeбо ћкw к0жу:</slav>
		<rus>Ты одеваешься светом, как ризою, простираешь небеса, как шатер;</rus>
	</verse>
	<verse nr="3">
		<slav>
			<num>G</num> покрывazй водaми превhспрєннzz сво‰, полагazй w4блаки на восхождeніе своE, ходsй на крил{ вётрєню:</slav>
		<rus>устрояешь над водами горние чертоги Твои, делаешь облака Твоею колесницею, шествуешь на крыльях ветра.</rus>
	</verse>
	<verse nr="4">
		<slav>
			<num>д7</num> творsй ѓгGлы сво‰ дyхи, и3 слуги6 сво‰ плaмень џгненный:</slav>
		<rus>Ты творишь ангелами Твоими духов, служителями Твоими - огонь пылающий.</rus>
	</verse>
	<verse nr="5">
		<slav>
			<num>є7</num> њсновazй зeмлю на твeрди є3S: не преклони1тсz въ вёкъ вёка.</slav>
		<rus>Ты поставил землю на твердых основах: не поколеблется она во веки и веки.</rus>
	</verse>
	<verse nr="6">
		<slav>
			<num>ѕ7</num> Бeздна ћкw ри1за њдэsніе є3S, на горaхъ стaнутъ в0ды:</slav>
		<rus>Бездною, как одеянием, покрыл Ты ее, на горах стоят воды.</rus>
	</verse>
	<verse nr="7">
		<slav>
			<num>з7</num> t запрещeніz твоегw2 побёгнутъ, t глaса гр0ма твоегw2 ўбоsтсz.</slav>
		<rus>От прещения Твоего бегут они, от гласа грома Твоего быстро уходят;</rus>
	</verse>
	<verse nr="8">
		<slav>
			<num>}</num> Восх0дzтъ г0ры, и3 низх0дzтъ полS, въ мёсто є4же њсновaлъ є3си2 и5мъ.</slav>
		<rus>восходят на горы, нисходят в долины, на место, которое Ты назначил для них.</rus>
	</verse>
	<verse nr="9">
		<slav>
			<num>f7</num> Предёлъ положи1лъ є3си2, є3гHже не прeйдутъ, нижE њбратsтсz покрhти зeмлю.</slav>
		<rus>Ты положил предел, которого не перейдут, и не возвратятся покрыть землю.</rus>
	</verse>
	<verse nr="10">
		<slav>
			<num>‹</num> Посылazй и3ст0чники въ дeбрехъ, посредЁ г0ръ пр0йдутъ в0ды.</slav>
		<rus>Ты послал источники в долины: между горами текут [воды],</rus>
	</verse>
	<verse nr="11">
		<slav>
			<num>№i</num> Напаsютъ вс‰ ѕвBри сє1лныz, ждyтъ (воспріи1мутъ) nнaгри въ жaжду свою2.</slav>
		<rus>поят всех полевых зверей; дикие ослы утоляют жажду свою.</rus>
	</verse>
	<verse nr="12">
		<slav>
			<num>в7i</num> На тhхъ пти6цы небє1сныz привитaютъ: t среды2 кaменіz дадsтъ глaсъ.</slav>
		<rus>При них обитают птицы небесные, из среды ветвей издают голос.</rus>
	</verse>
	<verse nr="13">
		<slav>
			<num>Gi</num> Напаszй г0ры t превhспреннихъ свои1хъ: t плодA дёлъ твои1хъ насhтитсz землS.</slav>
		<rus>Ты напояешь горы с высот Твоих, плодами дел Твоих насыщается земля.</rus>
	</verse>
	<verse nr="14">
		<slav>
			<num>д7i</num> Прозzбazй травY скотHмъ, и3 ѕлaкъ на слyжбу человёкwмъ, и3звести2 хлёбъ t земли2:</slav>
		<rus>Ты произращаешь траву для скота, и зелень на пользу человека, чтобы произвести из земли пищу,</rus>
	</verse>
	<verse nr="15">
		<slav>
			<num>є7i</num> и3 віно2 весели1тъ сeрдце человёка, ўмaстити лицE є3лeемъ: и3 хлёбъ сeрдце человёка ўкрэпи1тъ.</slav>
		<rus>и вино, которое веселит сердце человека, и елей, от которого блистает лице его, и хлеб, который укрепляет сердце человека.</rus>
	</verse>
	<verse nr="16">
		<slav>
			<num>ѕ7i</num> Насhтzтсz древA пwльскaz, кeдри лівaнстіи, и5хже є3си2 насади1лъ:</slav>
		<rus>Насыщаются древа Господа, кедры Ливанские, которые Он насадил;</rus>
	</verse>
	<verse nr="17">
		<slav>
			<num>з7i</num> тaмw пти6цы вогнэздsтсz, є3рwдjево жили1ще предводи1телствуетъ и4ми.</slav>
		<rus>на них гнездятся птицы: ели - жилище аисту,</rus>
	</verse>
	<verse nr="18">
		<slav>
			<num>}i</num> Г0ры высHкіz є3лeнємъ, кaмень прибёжище зazцємъ.</slav>
		<rus>высокие горы - сернам; каменные утесы - убежище зайцам.</rus>
	</verse>
	<verse nr="19">
		<slav>
			<num>f7i</num> Сотвори1лъ є4сть лунY во временA: с0лнце познA зaпадъ св0й.</slav>
		<rus>Он сотворил луну для указания времен, солнце знает свой запад.</rus>
	</verse>
	<verse nr="20">
		<slav>
			<num>к7</num> Положи1лъ є3си2 тмY, и3 бhсть н0щь, въ нeйже пр0йдутъ вси2 ѕвёріе дубрaвніи,</slav>
		<rus>Ты простираешь тьму и бывает ночь: во время нее бродят все лесные звери;</rus>
	</verse>
	<verse nr="21">
		<slav>
			<num>к7а</num> скЂмни рыкaющіи восхи1тити и3 взыскaти t бGа пи1щу себЁ.</slav>
		<rus>львы рыкают о добыче и просят у Бога пищу себе.</rus>
	</verse>
	<verse nr="22">
		<slav>
			<num>к7в</num> ВозсіS с0лнце, и3 собрaшасz, и3 въ л0жахъ свои1хъ лsгутъ.</slav>
		<rus>Восходит солнце, [и] они собираются и ложатся в свои логовища;</rus>
	</verse>
	<verse nr="23">
		<slav>
			<num>к7г</num> И#зhдетъ человёкъ на дёло своE и3 на дёланіе своE до вeчера.</slav>
		<rus>выходит человек на дело свое и на работу свою до вечера.</rus>
	</verse>
	<verse nr="24">
		<slav>
			<num>к7д</num> Ћкw возвели1чишасz дэлA тво‰, гDи: вс‰ премdростію сотвори1лъ є3си2: и3сп0лнисz землS твaри твоеS.</slav>
		<rus>Как многочисленны дела Твои, Господи! Все соделал Ты премудро; земля полна произведений Твоих.</rus>
	</verse>
	<verse nr="25">
		<slav>
			<num>к7є</num> СіE м0ре вели1кое и3 прострaнное: тaмw гaди, и4хже нёсть числA, живHтнаz м†лаz съ вели1кими:</slav>
		<rus>Это - море великое и пространное: там пресмыкающиеся, которым нет числа, животные малые с большими;</rus>
	</verse>
	<verse nr="26">
		<slav>
			<num>к7ѕ</num> тaмw корабли6 преплaваютъ, ѕмjй сeй, є3г0же создaлъ є3си2 ругaтисz є3мY.</slav>
		<rus>там плавают корабли, там этот левиафан, которого Ты сотворил играть в нем.</rus>
	</verse>
	<verse nr="27">
		<slav>
			<num>к7з</num> Вс‰ къ тебЁ чaютъ, дaти пи1щу и5мъ во блaго врeмz.</slav>
		<rus>Все они от Тебя ожидают, чтобы Ты дал им пищу их в свое время.</rus>
	</verse>
	<verse nr="28">
		<slav>
			<num>к7и</num> Дaвшу тебЁ и5мъ, соберyтъ: tвeрзшу тебЁ рyку, всsчєскаz и3сп0лнzтсz блaгости:</slav>
		<rus>Даешь им - принимают, отверзаешь руку Твою - насыщаются благом;</rus>
	</verse>
	<verse nr="29">
		<slav>
			<num>к7f</num> tврaщшу же тебЁ лицE, возмzтyтсz: tи1меши дyхъ и4хъ, и3 и3зчeзнутъ и3 въ пeрсть свою2 возвратsтсz:</slav>
		<rus>скроешь лице Твое - мятутся, отнимешь дух их - умирают и в персть свою возвращаются;</rus>
	</verse>
	<verse nr="30">
		<slav>
			<num>l</num> п0слеши д¦а твоего2, и3 сози1ждутсz, и3 њбнови1ши лицE земли2.</slav>
		<rus>пошлешь дух Твой - созидаются, и Ты обновляешь лице земли.</rus>
	</verse>
	<verse nr="31">
		<slav>
			<num>lа</num> Бyди слaва гDнz во вёки: возвесели1тсz гDь њ дёлэхъ свои1хъ:</slav>
		<rus>Да будет Господу слава во веки; да веселится Господь о делах Своих!</rus>
	</verse>
	<verse nr="32">
		<slav>
			<num>lв</num> призирazй на зeмлю и3 творsй ю5 трzсти1сz: прикасazйсz горaмъ, и3 дымsтсz.</slav>
		<rus>Призирает на землю, и она трясется; прикасается к горам, и дымятся.</rus>
	</verse>
	<verse nr="33">
		<slav>
			<num>lг</num> Воспою1 гDеви въ животЁ моeмъ, пою2 бGу моемY, д0ндеже є4смь:</slav>
		<rus>Буду петь Господу во всю жизнь мою, буду петь Богу моему, доколе есмь.</rus>
	</verse>
	<verse nr="34">
		<slav>
			<num>lд</num> да ўслади1тсz є3мY бесёда моS, ѓзъ же возвеселю1сz њ гDэ.</slav>
		<rus>Да будет благоприятна Ему песнь моя; буду веселиться о Господе.</rus>
	</verse>
	<verse nr="35">
		<slav>
			<num>lє</num> Да и3зчeзнутъ грBшницы t земли2, и3 беззакHнницы, ћкоже не бhти и5мъ. Благослови2, душE моS, гDа.</slav>
		<rus>Да исчезнут грешники с земли, и беззаконных да не будет более. Благослови, душа моя, Господа! Аллилуия!</rus>
	</verse>
</psalm>

=== alakim/slavbible/psalter/src/ps_91.xml
<?xml version="1.0" encoding="Windows-1251"?>
<!DOCTYPE psalm SYSTEM "psalm.dtd">
<?xml-stylesheet type="text/xsl" href="Page.xsl"?>
<psalm nr="91">
	<title>
		<num>№</num> Pал0мъ пёсни, въ дeнь суббHтный, <num>§а</num>.</title>
	<verse nr="1">
		<slav>
			<initial>Б</initial>lго є4сть и3сповёдатисz гDеви и3 пёти и4мени твоемY, вhшній:</slav>
		<rus>Благо есть славить Господа и петь имени Твоему, Всевышний,</rus>
	</verse>
	<verse nr="2">
		<slav>
			<num>G</num> возвэщaти заyтра млcть твою2 и3 истину твою2 на всsку н0щь,</slav>
		<rus>возвещать утром милость Твою и истину Твою в ночи,</rus>
	</verse>
	<verse nr="3">
		<slav>
			<num>д7</num> въ десzтострyннэмъ pалти1ри съ пёснію въ гyслехъ.</slav>
		<rus>на десятиструнном и псалтири, с песнью на гуслях.</rus>
	</verse>
	<verse nr="4">
		<slav>
			<num>є7</num> Ћкw возвесели1лъ мS є3си2, гDи, въ творeніи твоeмъ, и3 въ дёлэхъ рукY твоє1ю возрaдуюсz. </slav>
		<rus>Ибо Ты возвеселил меня, Господи, творением Твоим: я восхищаюсь делами рук Твоих.</rus>
	</verse>
	<verse nr="5">
		<slav>
			<num>ѕ7</num> Ћкw возвели1чишасz дэлA тво‰, гDи: ѕэлw2 ўглуби1шасz помышлє1ніz тво‰.</slav>
		<rus>Как велики дела Твои, Господи! дивно глубоки помышления Твои!</rus>
	</verse>
	<verse nr="6">
		<slav>
			<num>з7</num> Мyжъ безyменъ не познaетъ, и3 неразуми1въ не разумёетъ си1хъ.</slav>
		<rus>Человек несмысленный не знает, и невежда не разумеет того.</rus>
	</verse>
	<verse nr="7">
		<slav>
			<num>}</num> ВнегдA прозzб0ща грBшницы ћкw травA, и3 проник0ша вси2 дёлающіи беззак0ніе, ћкw да потребsтсz въ вёкъ вёка:</slav>
		<rus>Тогда как нечестивые возникают, как трава, и делающие беззаконие цветут, чтобы исчезнуть на веки, -</rus>
	</verse>
	<verse nr="8">
		<slav>
			<num>f7</num> тh же вhшній во вёкъ, гDи.</slav>
		<rus>Ты, Господи, высок во веки!</rus>
	</verse>
	<verse nr="9">
		<slav>
			<num>‹</num> Ћкw сE, врази2 твои2, гDи, ћкw сE, врази2 твои2 поги1бнутъ, и3 разhдутсz вси2 дёлающіи беззак0ніе.</slav>
		<rus>Ибо вот, враги Твои, Господи, - вот, враги Твои гибнут, и рассыпаются все делающие беззаконие;</rus>
	</verse>
	<verse nr="10">
		<slav>
			<num>№i</num> И# вознесeтсz ћкw є3динор0га р0гъ м0й, и3 стaрость моS въ є3лeи масти1тэ:</slav>
		<rus>а мой рог Ты возносишь, как рог единорога, и я умащен свежим елеем;</rus>
	</verse>
	<verse nr="11">
		<slav>
			<num>в7i</num> и3 воззрЁ џко моE на враги2 мо‰, и3 востаю1щыz на мS лукaвнующыz ўслhшитъ ќхо моE.</slav>
		<rus>и око мое смотрит на врагов моих, и уши мои слышат о восстающих на меня злодеях.</rus>
	</verse>
	<verse nr="12">
		<slav>
			<num>Gi</num> Првdникъ ћкw фjніxъ процвэтeтъ: ћкw кeдръ, и4же въ лівaнэ, ўмн0житсz.</slav>
		<rus>Праведник цветет, как пальма, возвышается подобно кедру на Ливане.</rus>
	</verse>
	<verse nr="13">
		<slav>
			<num>д7i</num> Насаждeни въ домY гDни во дв0рэхъ бGа нaшегw процвэтyтъ:</slav>
		<rus>Насажденные в доме Господнем, они цветут во дворах Бога нашего;</rus>
	</verse>
	<verse nr="14">
		<slav>
			<num>є7i</num> є3щE ўмн0жатсz въ стaрости масти1тэ, и3 благопріeмлюще бyдутъ.</slav>
		<rus>они и в старости плодовиты, сочны и свежи,</rus>
	</verse>
	<verse nr="15">
		<slav>
			<num>ѕ7i</num> Да возвэстsтъ, ћкw прaвъ гDь бGъ нaшъ, и3 нёсть непрaвды въ нeмъ.</slav>
		<rus>чтобы возвещать, что праведен Господь, твердыня моя, и нет неправды в Нем.</rus>
	</verse>
</psalm>

=== alakim/slavbible/trunk/psalter/src/ps_6.xml
<?xml version="1.0" encoding="Windows-1251"?>
<!DOCTYPE psalm SYSTEM "psalm.dtd">
<?xml-stylesheet type="text/xsl" href="Page.xsl"?>
<psalm nr="6">
	<title>
		<num>№</num> Въ конeцъ, въ пёснехъ њ nсмёмъ, pал0мъ дв7ду, <num>ѕ7</num>.<rus>Начальнику хора. На восьмиструнном. Псалом Давида.</rus>
	</title>
	<verse nr="1">
		<slav>
			<initial>Г</initial>Dи, да не ћростію твоeю њбличи1ши менE, нижE гнёвомъ твои1мъ накaжеши менE. </slav>
		<rus>Господи! не в ярости Твоей обличай меня и не во гневе Твоем наказывай меня.</rus>
	</verse>
	<verse nr="2">
		<slav>
			<num>G</num> Поми1луй мS, гDи, ћкw нeмощенъ є4смь: и3зцэли1 мz, гDи, ћкw смzт0шасz кHсти мо‰,</slav>
		<rus>Помилуй меня, Господи, ибо я немощен; исцели меня, Господи, ибо кости мои потрясены;</rus>
	</verse>
	<verse nr="3">
		<slav>
			<num>д7</num> и3 душA моS смzтeсz ѕэлw2: и3 ты2, гDи, док0лэ;</slav>
		<rus>и душа моя сильно потрясена; Ты же, Господи, доколе?</rus>
	</verse>
	<verse nr="4">
		<slav>
			<num>є7</num> Њбрати1сz, гDи, и3збaви дyшу мою2, сп7си1 мz рaди млcти твоеS:</slav>
		<rus>Обратись, Господи, избавь душу мою, спаси меня ради милости Твоей,</rus>
	</verse>
	<verse nr="5">
		<slav>
			<num>ѕ7</num> ћкw нёсть въ смeрти поминazй тебE, во ѓдэ же кто2 и3сповёстсz тебЁ;</slav>
		<rus>ибо в смерти нет памятования о Тебе: во гробе кто будет славить Тебя?</rus>
	</verse>
	<verse nr="6">
		<slav>
			<num>з7</num> Ўтруди1хсz воздыхaніемъ мои1мъ, и3змhю на всsку н0щь л0же моE, слезaми мои1ми постeлю мою2 њмочY.</slav>
		<rus>Утомлен я воздыханиями моими: каждую ночь омываю ложе мое, слезами моими омочаю постель мою.</rus>
	</verse>
	<verse nr="7">
		<slav>
			<num>}</num> Смzтeсz t ћрости џко моE, њбетшaхъ во всёхъ вразёхъ мои1хъ.</slav>
		<rus>Иссохло от печали око мое, обветшало от всех врагов моих.</rus>
	</verse>
	<verse nr="8">
		<slav>
			<num>f7</num> Tступи1те t менє2, вси2 дёлающіи беззак0ніе, ћкw ўслhша гDь глaсъ плaча моегw2,</slav>
		<rus>Удалитесь от меня все, делающие беззаконие, ибо услышал Господь голос плача моего,</rus>
	</verse>
	<verse nr="9">
		<slav>
			<num>‹</num> ўслhша гDь молeніе моE, гDь моли1тву мою2 пріsтъ.</slav>
		<rus>услышал Господь моление мое; Господь примет молитву мою.</rus>
	</verse>
	<verse nr="10">
		<slav>
			<num>№i</num> Да постыдsтсz и3 смzтyтсz вси2 врази2 мои2, да возвратsтсz и3 ўстыдsтсz ѕэлw2 вск0рэ.</slav>
		<rus>Да будут постыжены и жестоко поражены все враги мои; да возвратятся и постыдятся мгновенно.</rus>
	</verse>
</psalm>

=== alakim/slavbible/psalter/src/ps_127.xml
<?xml version="1.0" encoding="Windows-1251"?>
<!DOCTYPE psalm SYSTEM "psalm.dtd">
<?xml-stylesheet type="text/xsl" href="Page.xsl"?>
<psalm nr="127">
	<title>Пёснь степeней, <num>рк7з</num>.</title>
	<verse nr="1">
		<slav>
			<initial>Б</initial>lжeни вси2 боsщіисz гDа, ходsщіи въ путeхъ є3гw2:</slav>
		<rus>Блажен всякий боящийся Господа, ходящий путями Его!</rus>
	</verse>
	<verse nr="2">
		<slav>
			<num>в7</num> труды2 плодHвъ (рyкъ) твои1хъ снёси: бlжeнъ є3си2, и3 добро2 тебЁ бyдетъ.</slav>
		<rus>Ты будешь есть от трудов рук твоих: блажен ты, и благо тебе!</rus>
	</verse>
	<verse nr="3">
		<slav>
			<num>G</num> ЖенA твоS ћкw лозA плодови1та въ странaхъ д0му твоегw2:</slav>
		<rus>Жена твоя, как плодовитая лоза, в доме твоем; сыновья твои, как масличные ветви, вокруг трапезы твоей:</rus>
	</verse>
	<verse nr="4">
		<slav>
			<num>д7</num> сhнове твои2 ћкw новосаждє1ніz м†сличнаz w4крестъ трапeзы твоеS.</slav>
		<rus>так благословится человек, боящийся Господа!</rus>
	</verse>
	<verse nr="5">
		<slav>
			<num>є7</num> СE, тaкw бlгослови1тсz человёкъ боsйсz гDа.</slav>
		<rus>Благословит тебя Господь с Сиона, и увидишь благоденствие Иерусалима во все дни жизни твоей;</rus>
	</verse>
	<verse nr="6">
		<slav>
			<num>ѕ7</num> Блгcви1тъ тS гDь t сіHна, и3 ќзриши бlг†z їерcли1ма вс‰ дни6 животA твоегw2,</slav>
		<rus>увидишь сыновей у сыновей твоих. Мир на Израиля!</rus>
	</verse>
	<verse nr="7">
		<slav>
			<num>з7</num> и3 ќзриши сhны сынHвъ твои1хъ: ми1ръ на ї}лz.</slav>
		<rus/>
	</verse>
</psalm>

=== alakim/slavbible/trunk/psalter/src/ps_26.xml
<?xml version="1.0" encoding="Windows-1251"?>
<!DOCTYPE psalm SYSTEM "psalm.dtd">
<?xml-stylesheet type="text/xsl" href="Page.xsl"?>
<psalm nr="26">
	<title>Pал0мъ дв7ду, прeжде помaзаніz, <num>к7ѕ</num>.</title>
	<verse nr="1">
		<slav>
			<initial>Г</initial>Dь просвэщeніе моE и3 сп7си1тель м0й, когw2 ўбою1сz; гDь защи1титель животA моегw2, t когw2 ўстрашyсz;</slav>
		<rus>Господь - свет мой и спасение мое: кого мне бояться? Господь крепость жизни моей: кого мне страшиться?</rus>
	</verse>
	<verse nr="2">
		<slav>
			<num>в7</num> ВнегдA приближaтисz на мS ѕл0бующымъ, є4же снёсти плHти мо‰, њскорблsющіи мS и3 врази2 мои2, тjи и3знемог0ша и3 пад0ша.</slav>
		<rus>Если будут наступать на меня злодеи, противники и враги мои, чтобы пожрать плоть мою, то они сами преткнутся и падут.</rus>
	</verse>
	<verse nr="3">
		<slav>
			<num>G</num> Ѓще њполчи1тсz на мS п0лкъ, не ўбои1тсz сeрдце моE: ѓще востaнетъ на мS брaнь, на него2 ѓзъ ўповaю.</slav>
		<rus>Если ополчится против меня полк, не убоится сердце мое; если восстанет на меня война, и тогда буду надеяться.</rus>
	</verse>
	<verse nr="4">
		<slav>
			<num>д7</num> Е#ди1но проси1хъ t гDа, то2 взыщY: є4же жи1ти ми2 въ домY гDни вс‰ дни6 животA моегw2, зрёти ми2 красотY гDню и3 посэщaти хрaмъ с™hй є3гw2.</slav>
		<rus>Одного просил я у Господа, того только ищу, чтобы пребывать мне в доме Господнем во все дни жизни моей, созерцать красоту Господню и посещать [святый] храм Его,</rus>
	</verse>
	<verse nr="5">
		<slav>
			<num>є7</num> Ћкw скрh мz въ селeніи своeмъ въ дeнь ѕHлъ мои1хъ, покрh мz въ тaйнэ селeніz своегw2, на кaмень вознесe мz.</slav>
		<rus>ибо Он укрыл бы меня в скинии Своей в день бедствия, скрыл бы меня в потаенном месте селения Своего, вознес бы меня на скалу.</rus>
	</verse>
	<verse nr="6">
		<slav>
			<num>ѕ7</num> И# нн7э сE, вознесE главY мою2 на враги2 мо‰: њбыд0хъ и3 пожр0хъ въ селeніи є3гw2 жeртву хвалeніz и3 воскликновeніz: пою2 и3 воспою2 гDеви.</slav>
		<rus>Тогда вознеслась бы голова моя над врагами, окружающими меня; и я принес бы в Его скинии жертвы славословия, стал бы петь и воспевать пред Господом.</rus>
	</verse>
	<verse nr="7">
		<slav>
			<num>з7</num> Ўслhши, гDи, глaсъ м0й, и4мже воззвaхъ, поми1луй мS и3 ўслhши мS.</slav>
		<rus>Услышь, Господи, голос мой, которым я взываю, помилуй меня и внемли мне.</rus>
	</verse>
	<verse nr="8">
		<slav>
			<num>}</num> ТебЁ речE сeрдце моE: гDа взыщY, взыскA тебE лицE моE, лицA твоегw2, гDи, взыщY.</slav>
		<rus>Сердце мое говорит от Тебя: [ищите лица Моего]; и я буду искать лица Твоего, Господи.</rus>
	</verse>
	<verse nr="9">
		<slav>
			<num>f7</num> Не tврати2 лицA твоегw2 t менє2 и3 не ўклони1сz гнёвомъ t рабA твоегw2: пом0щникъ м0й бyди, не tри1ни менE и3 не њстaви менE, б9е, сп7си1телю м0й.</slav>
		<rus>Не скрой от меня лица Твоего; не отринь во гневе раба Твоего. Ты был помощником моим; не отвергни меня и не оставь меня, Боже, Спаситель мой!</rus>
	</verse>
	<verse nr="10">
		<slav>
			<num>‹</num> Ћкw nтeцъ м0й и3 мaти моS њстaвиста мS, гDь же воспріsтъ мS.</slav>
		<rus>ибо отец мой и мать моя оставили меня, но Господь примет меня.</rus>
	</verse>
	<verse nr="11">
		<slav>
			<num>№i</num> Законоположи1 ми, гDи, въ пути2 твоeмъ, и3 настaви мS на стезю2 прaвую вр†гъ мои1хъ рaди.</slav>
		<rus>Научи меня, Господи, пути Твоему и наставь меня на стезю правды, ради врагов моих;</rus>
	</verse>
	<verse nr="12">
		<slav>
			<num>в7i</num> Не предaждь менE въ дyшы стужaющихъ ми2: ћкw востaша на мS свидётелє непрaведніи, и3 солгA непрaвда себЁ.</slav>
		<rus>не предавай меня на произвол врагам моим, ибо восстали на меня свидетели лживые и дышат злобою.</rus>
	</verse>
	<verse nr="13">
		<slav>
			<num>Gi</num> Вёрую ви1дэти бlг†z гDнz на земли2 живhхъ.</slav>
		<rus>Но я верую, что увижу благость Господа на земле живых.</rus>
	</verse>
	<verse nr="14">
		<slav>
			<num>д7i</num> Потерпи2 гDа, мужaйсz, и3 да крэпи1тсz сeрдце твоE, и3 потерпи2 гDа.</slav>
		<rus>Надейся на Господа, мужайся, и да укрепляется сердце твое, и надейся на Господа.</rus>
	</verse>
</psalm>

=== alakim/slavbible/psalter/src/ps_64.xml
<?xml version="1.0" encoding="Windows-1251"?>
<!DOCTYPE psalm SYSTEM "psalm.dtd">
<?xml-stylesheet type="text/xsl" href="Page.xsl"?>
<psalm nr="64">
	<title>
		<num>№</num> Въ конeцъ, pал0мъ пёсни дв7ду, пёснь їеремjева и3 їезекjилева, людjй преселeніz, є3гдA хотsху и3сходи1ти, <num>…д</num>.</title>
	<verse nr="1">
		<slav>
			<initial>Т</initial>ебЁ подобaетъ пёснь, б9е, въ сіHнэ, и тебЁ воздaстсz моли1тва во їерcли1мэ.</slav>
		<rus>Тебе, Боже, принадлежит хвала на Сионе, и Тебе воздастся обет [в Иерусалиме].</rus>
	</verse>
	<verse nr="2">
		<slav>
			<num>G</num> Ўслhши моли1тву мою2: къ тебЁ всsка пл0ть пріи1детъ.</slav>
		<rus>Ты слышишь молитву; к Тебе прибегает всякая плоть.</rus>
	</verse>
	<verse nr="3">
		<slav>
			<num>д7</num> СловесA беззакHнникъ премог0ша нaсъ: и3 нечє1стіz н†ша ты2 њчтcиши.</slav>
		<rus>Дела беззаконий превозмогают меня; Ты очистишь преступления наши.</rus>
	</verse>
	<verse nr="4">
		<slav>
			<num>є7</num> Бlжeнъ, є3г0же и3збрaлъ є3си2 и3 пріsлъ, всели1тсz во дв0рэхъ твои1хъ. И#сп0лнимсz во бlги1хъ д0му твоегw2: с™ъ хрaмъ тв0й.</slav>
		<rus>Блажен, кого Ты избрал и приблизил, чтобы он жил во дворах Твоих. Насытимся благами дома Твоего, святаго храма Твоего.</rus>
	</verse>
	<verse nr="5">
		<slav>
			<num>ѕ7</num> Ди1венъ въ прaвдэ, ўслhши ны2, б9е, сп7си1телю нaшъ, ўповaніе всёхъ концeй земли2 и3 сyщихъ въ м0ри далeче:</slav>
		<rus>Страшный в правосудии, услышь нас, Боже, Спаситель наш, упование всех концов земли и находящихся в море далеко,</rus>
	</verse>
	<verse nr="6">
		<slav>
			<num>з7</num> ўготовлszй г0ры крёпостію своeю, препоsсанъ си1лою:</slav>
		<rus>поставивший горы силою Своею, препоясанный могуществом,</rus>
	</verse>
	<verse nr="7">
		<slav>
			<num>}</num> смущazй глубинY морскyю, шyму в0лнъ є3гw2 кто2 постои1тъ; смzтyтсz kзhцы,</slav>
		<rus>укрощающий шум морей, шум волн их и мятеж народов!</rus>
	</verse>
	<verse nr="8">
		<slav>
			<num>f7</num> и3 ўбоsтсz живyщіи въ концaхъ t знaменій твои1хъ: и3сх0ды ќтра и3 вeчера ўкраси1ши.</slav>
		<rus>И убоятся знамений Твоих живущие на пределах земли. Утро и вечер возбудишь к славе Твоей.</rus>
	</verse>
	<verse nr="9">
		<slav>
			<num>‹</num> Посэти1лъ є3си2 зeмлю и3 ўпои1лъ є3си2 ю5, ўмн0жилъ є3си2 њбогати1ти ю5: рэкA б9іz нап0лнисz в0дъ: ўгот0валъ є3си2 пи1щу и5мъ, ћкw тaкw (є4сть) ўгот0ваніе.</slav>
		<rus>Ты посещаешь землю и утоляешь жажду ее, обильно обогащаешь ее: поток Божий полон воды; Ты приготовляешь хлеб, ибо так устроил ее;</rus>
	</verse>
	<verse nr="10">
		<slav>
			<num>№i</num> Бразды6 є3S ўп0й, ўмн0жи жи6та є3S: въ кaплzхъ є3S возвесели1тсz возсіsющи (прозzбaющи).</slav>
		<rus>напояешь борозды ее, уравниваешь глыбы ее, размягчаешь ее каплями дождя, благословляешь произрастания ее;</rus>
	</verse>
	<verse nr="11">
		<slav>
			<num>в7i</num> Блгcви1ши вэнeцъ лёта блaгости твоеS, и3 полS тво‰ и3сп0лнzтсz тyка:</slav>
		<rus>венчаешь лето благости Твоей, и стези Твои источают тук,</rus>
	</verse>
	<verse nr="12">
		<slav>
			<num>Gi</num> разботёютъ кр†снаz пустhни, и3 рaдостію х0лми препоsшутсz.</slav>
		<rus>источают на пустынные пажити, и холмы препоясываются радостью;</rus>
	</verse>
	<verse nr="13">
		<slav>
			<num>д7i</num> Њдёzшасz џвни џвчіи, и3 ўдHліz ўмн0жатъ пшени1цу: воззовyтъ, и4бо воспою1тъ.</slav>
		<rus>луга одеваются стадами, и долины покрываются хлебом, восклицают и поют.</rus>
	</verse>
</psalm>

=== alakim/slavbible/psalter/src/ps_66.xml
<?xml version="1.0" encoding="Windows-1251"?>
<!DOCTYPE psalm SYSTEM "psalm.dtd">
<?xml-stylesheet type="text/xsl" href="Page.xsl"?>
<psalm nr="66">
	<title>
		<num>№</num> Въ конeцъ, въ пёснехъ, pал0мъ пёсни дв7ду, <num>…ѕ</num>.</title>
	<verse nr="1">
		<slav>
			<initial>Б</initial>9е, ўщeдри ны2 и3 блгcви1 ны, просвэти2 лицE твоE на ны2 и3 поми1луй ны2: </slav>
		<rus>Боже! будь милостив к нам и благослови нас, освети нас лицем Твоим,</rus>
	</verse>
	<verse nr="2">
		<slav>
			<num>G</num> Познaти на земли2 пyть тв0й, во всёхъ kзhцэхъ спcніе твоE.</slav>
		<rus>дабы познали на земле путь Твой, во всех народах спасение Твое.</rus>
	</verse>
	<verse nr="3">
		<slav>
			<num>д7</num> Да и3сповёдzтсz тебЁ лю1діе, б9е, да и3сповёдzтсz тебЁ лю1діе вси2.</slav>
		<rus>Да восхвалят Тебя народы, Боже; да восхвалят Тебя народы все.</rus>
	</verse>
	<verse nr="4">
		<slav>
			<num>є7</num> Да возвеселsтсz и3 да возрaдуютсz kзhцы: ћкw сyдиши лю1демъ правот0ю, и3 kзhки на земли2 настaвиши.</slav>
		<rus>Да веселятся и радуются племена, ибо Ты судишь народы праведно и управляешь на земле племенами.</rus>
	</verse>
	<verse nr="5">
		<slav>
			<num>ѕ7</num> Да и3сповёдzтсz тебЁ лю1діе, б9е, да и3сповёдzтсz тебЁ лю1діе вси2.</slav>
		<rus>Да восхвалят Тебя народы, Боже, да восхвалят Тебя народы все.</rus>
	</verse>
	<verse nr="6">
		<slav>
			<num>з7</num> ЗемлS дадE пл0дъ св0й: блгcви1 ны, б9е, б9е нaшъ,</slav>
		<rus>Земля дала плод свой; да благословит нас Бог, Бог наш.</rus>
	</verse>
	<verse nr="7">
		<slav>
			<num>}</num> блгcви1 ны, б9е: и3 да ўбоsтсz є3гw2 вси2 концы6 земли2.</slav>
		<rus>Да благословит нас Бог, и да убоятся Его все пределы земли.</rus>
	</verse>
</psalm>

=== alakim/slavbible/psalter/src/ps_27.xml
<?xml version="1.0" encoding="Windows-1251"?>
<!DOCTYPE psalm SYSTEM "psalm.dtd">
<?xml-stylesheet type="text/xsl" href="Page.xsl"?>
<psalm nr="27">
	<title>Pал0мъ дв7ду, <num>к7з</num>.</title>
	<verse nr="1">
		<slav>
			<initial>К</initial>ъ тебЁ, гDи, воззовY, б9е м0й: да не премолчи1ши t менє2 (њ мнЁ): да не когдA премолчи1ши t менє2 (њ мнЁ), и3 ўпод0блюсz низходsщымъ въ р0въ.</slav>
		<rus>К тебе, Господи, взываю: твердыня моя! не будь безмолвен для меня, чтобы при безмолвии Твоем я не уподобился нисходящим в могилу.</rus>
	</verse>
	<verse nr="2">
		<slav>
			<num>в7</num> Ўслhши, гDи, глaсъ молeніz моегw2, внегдA моли1тимисz къ тебЁ, внегдA воздёти ми2 рyцэ мои2 ко хрaму с™0му твоемY.</slav>
		<rus>Услышь голос молений моих, когда я взываю к Тебе, когда поднимаю руки мои к святому храму Твоему.</rus>
	</verse>
	<verse nr="3">
		<slav>
			<num>G</num> Не привлецы2 менE со грBшники, и3 съ дёлающими непрaвду не погуби2 менE, глаг0лющими ми1ръ съ бли1жними свои1ми, ѕл†z же въ сердцaхъ свои1хъ.</slav>
		<rus>Не погуби меня с нечестивыми и с делающими неправду, которые с ближними своими говорят о мире, а в сердце у них зло.</rus>
	</verse>
	<verse nr="4">
		<slav>
			<num>д7</num> Дaждь и5мъ, гDи, по дэлHмъ и4хъ и3 по лукaвству начинaній и4хъ, по дэлHмъ рукY и4хъ дaждь и5мъ, воздaждь воздаsніе и4хъ и5мъ.</slav>
		<rus>Воздай им по делам их, по злым поступкам их; по делам рук их воздай им, отдай им заслуженное ими.</rus>
	</verse>
	<verse nr="5">
		<slav>
			<num>є7</num> Ћкw не разумёша въ дэлA гDнz и3 въ дэлA рукY єгw2: разори1ши | и3 не сози1ждеши |.</slav>
		<rus>За то, что они невнимательны к действиям Господа и к делу рук Его, Он разрушит их и не созиждет их.</rus>
	</verse>
	<verse nr="6">
		<slav>
			<num>ѕ7</num> Блгcвeнъ гDь, ћкw ўслhша глaсъ молeніz моегw2.</slav>
		<rus>Благословен Господь, ибо Он услышал голос молений моих.</rus>
	</verse>
	<verse nr="7">
		<slav>
			<num>з7</num> ГDь пом0щникъ м0й и3 защи1титель м0й: на него2 ўповA сeрдце моE, и3 пом0же ми2, и3 процвэтE пл0ть моS: и3 в0лею моeю и3сповёмсz є3мY.</slav>
		<rus>Господь - крепость моя и щит мой; на Него уповало сердце мое, и Он помог мне, и возрадовалось сердце мое; и я прославлю Его песнью моею.</rus>
	</verse>
	<verse nr="8">
		<slav>
			<num>}</num> ГDь ўтверждeніе людjй свои1хъ и3 защи1титель спасeній хрістA своегw2 є4сть.</slav>
		<rus>Господь - крепость народа Своего и спасительная защита помазанника Своего.</rus>
	</verse>
	<verse nr="9">
		<slav>
			<num>f7</num> Сп7си2 лю1ди тво‰, и3 блгcви2 достоsніе твоE, и3 ўпаси2 |, и3 возми2 (и3 вознеси2) | до вёка.</slav>
		<rus>Спаси народ Твой и благослови наследие Твое; паси их и возвышай их во веки!</rus>
	</verse>
</psalm>
