=== alakim/slavbible/trunk/psalter/src/psalm.dtd
<!ELEMENT psalm (title, verse*)>
<!ATTLIST psalm
	nr CDATA #REQUIRED
>
<!ELEMENT verse (#PCDATA | slav | rus)*>
<!ATTLIST verse
	nr CDATA #REQUIRED
>
<!ELEMENT num (#PCDATA)>
<!ELEMENT initial (#PCDATA)>
<!ELEMENT title (#PCDATA | num | rus)*>
<!ELEMENT rus (#PCDATA)>
<!ELEMENT slav (#PCDATA | num | initial)*>

=== alakim/slavbible/trunk/psalter/src/ps_84.xml
<?xml version="1.0" encoding="Windows-1251"?>
<!DOCTYPE psalm SYSTEM "psalm.dtd">
<?xml-stylesheet type="text/xsl" href="Page.xsl"?>
<psalm nr="84">
	<title>
		<num>№</num> Въ конeцъ, сынHмъ корewвымъ, pал0мъ, <num>п7д</num>.</title>
	<verse nr="1">
		<slav>
			<initial>Б</initial>lговоли1лъ є3си2, гDи, зeмлю твою2, возврати1лъ є3си2 плёнъ їaкwвль.</slav>
		<rus>Господи! Ты умилосердился к земле Твоей, возвратил плен Иакова;</rus>
	</verse>
	<verse nr="2">
		<slav>
			<num>G</num> Њстaвилъ є3си2 беззакHніz людjй твои1хъ, покрhлъ є3си2 вс‰ грэхи2 и4хъ.</slav>
		<rus>простил беззаконие народа Твоего, покрыл все грехи его,</rus>
	</verse>
	<verse nr="3">
		<slav>
			<num>д7</num> Ўкроти1лъ є3си2 вeсь гнёвъ тв0й, возврати1лсz є3си2 t гнёва ћрости твоеS.</slav>
		<rus>отъял всю ярость Твою, отвратил лютость гнева Твоего.</rus>
	</verse>
	<verse nr="4">
		<slav>
			<num>є7</num> Возврати2 нaсъ, б9е спcній нaшихъ, и3 tврати2 ћрость твою2 t нaсъ.</slav>
		<rus>Восстанови нас, Боже спасения нашего, и прекрати негодование Твое на нас.</rus>
	</verse>
	<verse nr="5">
		<slav>
			<num>ѕ7</num> Е#дA во вёки прогнёваешисz на ны2; и3ли2 прострeши гнёвъ тв0й t р0да въ р0дъ;</slav>
		<rus>Неужели вечно будешь гневаться на нас, прострешь гнев Твой от рода в род?</rus>
	</verse>
	<verse nr="6">
		<slav>
			<num>з7</num> Б9е, ты2 њбрaщьсz њживи1ши ны2, и3 лю1діе твои2 возвеселsтсz њ тебЁ.</slav>
		<rus>Неужели снова не оживишь нас, чтобы народ Твой возрадовался о Тебе?</rus>
	</verse>
	<verse nr="7">
		<slav>
			<num>}</num> Kви2 нaмъ, гDи, млcть твою2, и3 спcніе твоE дaждь нaмъ.</slav>
		<rus>Яви нам, Господи, милость Твою, и спасение Твое даруй нам.</rus>
	</verse>
	<verse nr="8">
		<slav>
			<num>f7</num> Ўслhшу, что2 речeтъ њ мнЁ гDь бGъ: ћкw речeтъ ми1ръ на лю1ди сво‰, и3 на прпdбныz сво‰, и3 на њбращaющыz сердцA къ немY.</slav>
		<rus>Послушаю, что скажет Господь Бог. Он скажет мир народу Своему и избранным Своим, но да не впадут они снова в безрассудство.</rus>
	</verse>
	<verse nr="9">
		<slav>
			<num>‹</num> Nбaче бли1з8 боsщихсz є3гw2 спcніе є3гw2, всели1ти слaву въ зeмлю нaшу.</slav>
		<rus>Так, близко к боящимся Его спасение Его, чтобы обитала слава в земле нашей!</rus>
	</verse>
	<verse nr="10">
		<slav>
			<num>№i</num> Млcть и3 и4стина срэт0стэсz, прaвда и3 ми1ръ њблобызaстасz:</slav>
		<rus>Милость и истина сретятся, правда и мир облобызаются;</rus>
	</verse>
	<verse nr="11">
		<slav>
			<num>в7i</num> и4стина t земли2 возсіz, и3 прaвда съ нб7сE прини1че:</slav>
		<rus>истина возникнет из земли, и правда приникнет с небес;</rus>
	</verse>
	<verse nr="12">
		<slav>
			<num>Gi</num> и4бо гDь дaстъ бlгость, и3 землS нaша дaстъ пл0дъ св0й.</slav>
		<rus>и Господь даст благо, и земля наша даст плод свой;</rus>
	</verse>
	<verse nr="13">
		<slav>
			<num>д7i</num> Прaвда пред8 ни1мъ пред8и1детъ, и3 положи1тъ въ пyть стwпы2 сво‰.</slav>
		<rus>правда пойдет пред Ним и поставит на путь стопы свои.</rus>
	</verse>
</psalm>

=== alakim/slavbible/psalter/src/ps_33.xml
<?xml version="1.0" encoding="Windows-1251"?>
<!DOCTYPE psalm SYSTEM "psalm.dtd">
<?xml-stylesheet type="text/xsl" href="Page.xsl"?>
<psalm nr="33">
	<title>
		<num>№</num> Pал0мъ дв7ду, внегдA и3змэни2 лицE своE пред8 ґвімелeхомъ: и3 tпусти2 є3го2, и3 tи1де, <num>lг</num>.</title>
	<verse nr="1">
		<slav>
			<initial>Б</initial>лагословлю2 гDа на всsкое врeмz, вhну хвалA є3гw2 во ўстёхъ мои1хъ.</slav>
		<rus>Благословлю Господа во всякое время; хвала Ему непрестанно в устах моих.</rus>
	</verse>
	<verse nr="2">
		<slav>
			<num>G</num> Њ гDэ похвaлитсz душA моS: да ўслhшатъ кр0тцыи и3 возвеселsтсz.</slav>
		<rus>Господом будет хвалиться душа моя; услышат кроткие и возвеселятся.</rus>
	</verse>
	<verse nr="3">
		<slav>
			<num>д7</num> Возвели1чите гDа со мн0ю, и3 вознесeмъ и4мz є3гw2 вкyпэ.</slav>
		<rus>Величайте Господа со мною, и превознесем имя Его вместе.</rus>
	</verse>
	<verse nr="4">
		<slav>
			<num>є7</num> Взыскaхъ гDа, и3 ўслhша мS и3 t всёхъ скорбeй мои1хъ и3збaви мS. </slav>
		<rus>Я взыскал Господа, и Он услышал меня, и от всех опасностей моих избавил меня.</rus>
	</verse>
	<verse nr="5">
		<slav>
			<num>ѕ7</num> Приступи1те къ немY и3 просвэти1тесz, и3 ли1ца в†ша не постыдsтсz. </slav>
		<rus>Кто обращал взор к Нему, те просвещались, и лица их не постыдятся.</rus>
	</verse>
	<verse nr="6">
		<slav>
			<num>з7</num> Сeй ни1щій воззвA, и3 гDь ўслhша и5, и3 t всёхъ скорбeй є3гw2 сп7сE и5.</slav>
		<rus>Сей нищий воззвал, - и Господь услышал и спас его от всех бед его.</rus>
	</verse>
	<verse nr="7">
		<slav>
			<num>}</num> Њполчи1тсz ѓгGлъ гDень w4крестъ боsщихсz є3гw2 и3 и3збaвитъ и5хъ.</slav>
		<rus>Ангел Господень ополчается вокруг боящихся Его и избавляет их.</rus>
	</verse>
	<verse nr="8">
		<slav>
			<num>f7</num> Вкуси1те и3 ви1дите, ћкw бlгъ гDь: бlжeнъ мyжъ, и4же ўповaетъ нaнь.  </slav>
		<rus>Вкусите, и увидите, как благ Господь! Блажен человек, который уповает на Него!</rus>
	</verse>
	<verse nr="9">
		<slav>
			<num>‹</num> Б0йтесz гDа, вси2 с™jи є3гw2, ћкw нёсть лишeніz боsщымсz є3гw2.</slav>
		<rus>Бойтесь Господа, [все] святые Его, ибо нет скудости у боящихся Его.</rus>
	</verse>
	<verse nr="10">
		<slav>
			<num>№i</num> Богaтіи њбнищaша и3 взалкaша: взыскaющіи же гDа не лишaтсz всsкагw блaга.</slav>
		<rus>Скимны бедствуют и терпят голод, а ищущие Господа не терпят нужды ни в каком благе.</rus>
	</verse>
	<verse nr="11">
		<slav>
			<num>в7i</num> Пріиди1те, ч†да, послyшайте менє2, стрaху гDню научY вaсъ.</slav>
		<rus>Придите, дети, послушайте меня: страху Господню научу вас.</rus>
	</verse>
	<verse nr="12">
		<slav>
			<num>Gi</num> Кт0 є3сть человёкъ хотsй жив0тъ, любsй дни6 ви1дэти блaги;</slav>
		<rus>Хочет ли человек жить и любит ли долгоденствие, чтобы видеть благо?</rus>
	</verse>
	<verse nr="13">
		<slav>
			<num>д7i</num> Ўдержи2 z3зhкъ тв0й t ѕлA и3 ўстнЁ твои2, є4же не глаг0лати льсти2.</slav>
		<rus>Удерживай язык свой от зла и уста свои от коварных слов.</rus>
	</verse>
	<verse nr="14">
		<slav>
			<num>є7i</num> Ўклони1сz t ѕлA и3 сотвори2 блaго: взыщи2 ми1ра и3 пожени2 и5.</slav>
		<rus>Уклоняйся от зла и делай добро; ищи мира и следуй за ним.</rus>
	</verse>
	<verse nr="15">
		<slav>
			<num>ѕ7i</num> Џчи гDни на првdныz, и3 ќши є3гw2 въ моли1тву и4хъ.</slav>
		<rus>Очи Господни обращены на праведников, и уши Его - к воплю их.</rus>
	</verse>
	<verse nr="16">
		<slav>
			<num>з7i</num> Лицe же гDне на творsщыz ѕл†z, є4же потреби1ти t земли2 пaмzть и4хъ.</slav>
		<rus>Но лице Господне против делающих зло, чтобы истребить с земли память о них.</rus>
	</verse>
	<verse nr="17">
		<slav>
			<num>}i</num> Воззвaша првdніи, и3 гDь ўслhша и5хъ и3 t всёхъ скорбeй и4хъ и3збaви и5хъ.</slav>
		<rus>Взывают [праведные], и Господь слышит, и от всех скорбей их избавляет их.</rus>
	</verse>
	<verse nr="18">
		<slav>
			<num>f7i</num> Бли1з8 гDь сокрушeнныхъ сeрдцемъ, и3 смирє1нныz дyхомъ сп7сeтъ.</slav>
		<rus>Близок Господь к сокрушенным сердцем и смиренных духом спасет.</rus>
	</verse>
	<verse nr="19">
		<slav>
			<num>к7</num> МнHги скHрби првdнымъ, и3 t всёхъ и4хъ и3збaвитъ | гDь.</slav>
		<rus>Много скорбей у праведного, и от всех их избавит его Господь.</rus>
	</verse>
	<verse nr="20">
		<slav>
			<num>к7а</num> Храни1тъ гDь вс‰ кHсти и4хъ, ни є3ди1на t ни1хъ сокруши1тсz.</slav>
		<rus>Он хранит все кости его; ни одна из них не сокрушится.</rus>
	</verse>
	<verse nr="21">
		<slav>
			<num>к7в</num> Смeрть грёшникwвъ лютA, и3 ненави1дzщіи првdнаго прегрэшaтъ.</slav>
		<rus>Убьет грешника зло, и ненавидящие праведного погибнут.</rus>
	</verse>
	<verse nr="22">
		<slav>
			<num>к7г</num> И#збaвитъ гDь дyшы р†бъ свои1хъ, и3 не прегрэшaтъ вси2 ўповaющіи на него2.</slav>
		<rus>Избавит Господь душу рабов Своих, и никто из уповающих на Него не погибнет.</rus>
	</verse>
</psalm>

=== alakim/slavbible/psalter/src/ps_124.xml
<?xml version="1.0" encoding="Windows-1251"?>
<!DOCTYPE psalm SYSTEM "psalm.dtd">
<?xml-stylesheet type="text/xsl" href="Page.xsl"?>
<psalm nr="124">
	<title>Пёснь степeней, <num>рк7д</num>.</title>
	<verse nr="1">
		<slav>
			<initial>Н</initial>адёющіисz на гDа, ћкw горA сіHнъ: не подви1житсz въ вёкъ живhй во їерcли1мэ.</slav>
		<rus>Надеющийся на Господа, как гора Сион, не подвигнется: пребывает вовек.</rus>
	</verse>
	<verse nr="2">
		<slav>
			<num>в7</num> Г0ры w4крестъ є3гw2, и3 гDь w4крестъ людjй свои1хъ, tнн7э и3 до вёка.</slav>
		<rus>Горы окрест Иерусалима, а Господь окрест народа Своего отныне и вовек.</rus>
	</verse>
	<verse nr="3">
		<slav>
			<num>G</num> Ћкw не њстaвитъ гDь жезлA грёшныхъ на жрeбій првdныхъ, ћкw да не пр0струтъ првdніи въ беззакHніz рyкъ свои1хъ.</slav>
		<rus>Ибо не оставит [Господь] жезла нечестивых над жребием праведных, дабы праведные не простерли рук своих к беззаконию.</rus>
	</verse>
	<verse nr="4">
		<slav>
			<num>д7</num> Ўбlжи2, гDи, бlг‡z и3 пр†выz срdцемъ. </slav>
		<rus>Благотвори, Господи, добрым и правым в сердцах своих;</rus>
	</verse>
	<verse nr="5">
		<slav>
			<num>є7</num> Ўклонsющыzсz же въ развращє1ніz tведeтъ гDь съ дёлающими беззак0ніе: ми1ръ на ї}лz.</slav>
		<rus>а совращающихся на кривые пути свои да оставит Господь ходить с делающими беззаконие. Мир на Израиля!</rus>
	</verse>
</psalm>

=== alakim/slavbible/trunk/psalter/src/ps_53.xml
<?xml version="1.0" encoding="Windows-1251"?>
<!DOCTYPE psalm SYSTEM "psalm.dtd">
<?xml-stylesheet type="text/xsl" href="Page.xsl"?>
<psalm nr="53">
	<title>
		<num>№</num> Въ конeцъ, въ пёснехъ рaзума дв7ду, </title>
	<verse nr="1">
		<slav>
			<num>в7</num> внегдA пріити2  зіфeємъ и3 рещи2 саyлови: не сe ли, дв7дъ скрhсz въ нaсъ; <num>н7г</num>.</slav>
		<rus>когда пришли Зифеи и сказали Саулу: "не у нас ли скрывается Давид?"</rus>
	</verse>
	<verse nr="2">
		<slav>
			<initial>Б</initial>9е, во и4мz твоE сп7си1 мz и3 въ си1лэ твоeй суди1 ми.</slav>
		<rus>Боже! именем Твоим спаси меня, и силою Твоею суди меня.</rus>
	</verse>
	<verse nr="3">
		<slav>
			<num>д7</num> Б9е, ўслhши моли1тву мою2, внуши2 глаг0лы ќстъ мои1хъ:</slav>
		<rus>Боже! услышь молитву мою, внемли словам уст моих,</rus>
	</verse>
	<verse nr="4">
		<slav>
			<num>є7</num> ћкw чyждіи востaша на мS, и3 крёпцыи взыскaша дyшу мою2, и3 не предложи1ша бGа пред8 соб0ю.</slav>
		<rus>ибо чужие восстали на меня, и сильные ищут души моей; они не имеют Бога пред собою.</rus>
	</verse>
	<verse nr="5">
		<slav>
			<num>ѕ7</num> Сe бо, бGъ помогaетъ ми2, и3 гDь застyпникъ души2 моeй:</slav>
		<rus>Вот, Бог помощник мой; Господь подкрепляет душу мою.</rus>
	</verse>
	<verse nr="6">
		<slav>
			<num>з7</num> tврати1тъ ѕл†z врагHмъ мои6мъ: и4стиною твоeю потреби2 и5хъ.</slav>
		<rus>Он воздаст за зло врагам моим; истиною Твоею истреби их.</rus>
	</verse>
	<verse nr="7">
		<slav>
			<num>}</num> В0лею пожрY тебЁ, и3сповёмсz и4мени твоемY, гDи, ћкw бlго:</slav>
		<rus>Я усердно принесу Тебе жертву, прославлю имя Твое, Господи, ибо оно благо,</rus>
	</verse>
	<verse nr="8">
		<slav>
			<num>f7</num> ћкw t всsкіz печaли и3збaвилъ мS є3си2, и3 на враги2 мо‰ воззрЁ џко моE.</slav>
		<rus>ибо Ты избавил меня от всех бед, и на врагов моих смотрело око мое.</rus>
	</verse>
</psalm>

=== alakim/slavbible/trunk/psalter/src/ps_94.xml
<?xml version="1.0" encoding="Windows-1251"?>
<!DOCTYPE psalm SYSTEM "psalm.dtd">
<?xml-stylesheet type="text/xsl" href="Page.xsl"?>
<psalm nr="94">
	<title>ХвалA пёсни дв7ду, не надпи1санъ ў є3врє1й, <num>§д</num>.</title>
	<verse nr="1">
		<slav>
			<initial>П</initial>ріиди1те, возрaдуемсz гDеви, воскли1кнемъ бGу сп7си1телю нaшему:</slav>
		<rus>Приидите, воспоем Господу, воскликнем [Богу], твердыне спасения нашего;</rus>
	</verse>
	<verse nr="2">
		<slav>
			<num>в7</num> предвари1мъ лицE є3гw2 во и3сповёданіи, и3 во pалмёхъ воскли1кнемъ є3мY:</slav>
		<rus>предстанем лицу Его со славословием, в песнях воскликнем Ему,</rus>
	</verse>
	<verse nr="3">
		<slav>
			<num>G</num> ћкw бGъ вeлій гDь, и3 цRь вeлій по всeй земли2:</slav>
		<rus>ибо Господь есть Бог великий и Царь великий над всеми богами.</rus>
	</verse>
	<verse nr="4">
		<slav>
			<num>д7</num> ћкw въ руцЁ є3гw2 вси2 концы6 земли2, и3 высwты2 г0ръ тогw2 сyть.</slav>
		<rus>В Его руке глубины земли, и вершины гор - Его же;</rus>
	</verse>
	<verse nr="5">
		<slav>
			<num>є7</num> Ћкw тогw2 є4сть м0ре, и3 т0й сотвори2 є5, и3 сyшу рyцэ є3гw2 создaстэ.</slav>
		<rus>Его - море, и Он создал его, и сушу образовали руки Его.</rus>
	</verse>
	<verse nr="6">
		<slav>
			<num>ѕ7</num> Пріиди1те, поклони1мсz и3 припадeмъ є3мY, и3 восплaчемсz пред8 гDемъ сотв0ршимъ нaсъ:</slav>
		<rus>Приидите, поклонимся и припадем, преклоним колени пред лицем Господа, Творца нашего;</rus>
	</verse>
	<verse nr="7">
		<slav>
			<num>з7</num> ћкw т0й є4сть бGъ нaшъ, и3 мы2 лю1діе пaжити є3гw2 и3 џвцы руки2 є3гw2. Днeсь ѓще глaсъ є3гw2 ўслhшите,</slav>
		<rus>ибо Он есть Бог наш, и мы - народ паствы Его и овцы руки Его. О, если бы вы ныне послушали гласа Его:</rus>
	</verse>
	<verse nr="8">
		<slav>
			<num>}</num> не њжесточи1те сердeцъ вaшихъ, ћкw въ прогнёваніи, по дни2 и3скушeніz въ пустhни:</slav>
		<rus>"не ожесточите сердца вашего, как в Мериве, как в день искушения в пустыне,</rus>
	</verse>
	<verse nr="9">
		<slav>
			<num>f7</num> въ џньже (и3дёже) и3скуси1ша мS nтцы2 вaши, и3скуси1ша мS, и3 ви1дэша дэлA мо‰.</slav>
		<rus>где искушали Меня отцы ваши, испытывали Меня, и видели дело Мое.</rus>
	</verse>
	<verse nr="10">
		<slav>
			<num>‹</num> Четhредесzть лётъ негодовaхъ р0да тогw2, и3 рёхъ: прcнw заблуждaютъ сeрдцемъ, тjи же не познaша путjй мои1хъ:</slav>
		<rus>Сорок лет Я был раздражаем родом сим, и сказал: это народ, заблуждающийся сердцем; они не познали путей Моих,</rus>
	</verse>
	<verse nr="11">
		<slav>
			<num>№i</num> ћкw клsхсz во гнёвэ моeмъ, ѓще вни1дутъ въ пок0й м0й.</slav>
		<rus>и потому Я поклялся во гневе Моем, что они не войдут в покой Мой".</rus>
	</verse>
</psalm>

=== alakim/slavbible/trunk/psalter/src/ps_71.xml
<?xml version="1.0" encoding="Windows-1251"?>
<!DOCTYPE psalm SYSTEM "psalm.dtd">
<?xml-stylesheet type="text/xsl" href="Page.xsl"?>
<psalm nr="71">
	<title>Њ соломHнэ, pал0мъ дв7ду, <num>о7а</num>.</title>
	<verse nr="1">
		<slav>
			<initial>Б</initial>9е, сyдъ тв0й царeви дaждь, и3 прaвду твою2 сhну царeву:</slav>
		<rus>Боже! даруй царю Твой суд и сыну царя Твою правду,</rus>
	</verse>
	<verse nr="2">
		<slav>
			<num>в7</num> суди1ти лю1демъ твои6мъ въ прaвдэ и3 ни1щымъ твои6мъ въ судЁ.</slav>
		<rus>да судит праведно людей Твоих и нищих Твоих на суде;</rus>
	</verse>
	<verse nr="3">
		<slav>
			<num>G</num> Да воспріи1мутъ г0ры ми1ръ лю1демъ и3 х0лми прaвду.</slav>
		<rus>да принесут горы мир людям и холмы правду;</rus>
	</verse>
	<verse nr="4">
		<slav>
			<num>д7</num> Сyдитъ ни1щымъ людски6мъ, и3 спасeтъ сhны ўб0гихъ, и3 смири1тъ клеветникA.</slav>
		<rus>да судит нищих народа, да спасет сынов убогого и смирит притеснителя, -</rus>
	</verse>
	<verse nr="5">
		<slav>
			<num>є7</num> И# пребyдетъ съ с0лнцемъ, и3 прeжде луны2 р0да родHвъ.</slav>
		<rus>и будут бояться Тебя, доколе пребудут солнце и луна, в роды родов.</rus>
	</verse>
	<verse nr="6">
		<slav>
			<num>ѕ7</num> Сни1детъ ћкw д0ждь на руно2, и3 ћкw кaплz кaплющаz на зeмлю.</slav>
		<rus>Он сойдет, как дождь на скошенный луг, как капли, орошающие землю;</rus>
	</verse>
	<verse nr="7">
		<slav>
			<num>з7</num> Возсіsетъ во днeхъ є3гw2 прaвда и3 мн0жество ми1ра, д0ндеже tи1метсz лунA.</slav>
		<rus>во дни его процветет праведник, и будет обилие мира, доколе не престанет луна;</rus>
	</verse>
	<verse nr="8">
		<slav>
			<num>}</num> И# њбладaетъ t м0рz до м0рz, и3 t рёкъ до конє1цъ вселeнныz.</slav>
		<rus>он будет обладать от моря до моря и от реки до концов земли;</rus>
	</verse>
	<verse nr="9">
		<slav>
			<num>f7</num> Пред8 ни1мъ припадyтъ є3fі0плzне, и3 врази2 є3гw2 пeрсть поли1жутъ.</slav>
		<rus>падут пред ним жители пустынь, и враги его будут лизать прах;</rus>
	</verse>
	<verse nr="10">
		<slav>
			<num>‹</num> Цaріе fарсjйстіи и3 џстрови дaры принесyтъ, цaріе ґрaвстіи и савA дaры приведyтъ:</slav>
		<rus>цари Фарсиса и островов поднесут ему дань; цари Аравии и Савы принесут дары;</rus>
	</verse>
	<verse nr="11">
		<slav>
			<num>№i</num> и3 покл0нzтсz є3мY вси2 цaріе зeмстіи, вси2 kзhцы пораб0таютъ є3мY.</slav>
		<rus>и поклонятся ему все цари; все народы будут служить ему;</rus>
	</verse>
	<verse nr="12">
		<slav>
			<num>в7i</num> Ћкw и3збaви ни1ща t си1льна, и3 ўб0га, є3мyже не бЁ пом0щника.</slav>
		<rus>ибо он избавит нищего, вопиющего и угнетенного, у которого нет помощника.</rus>
	</verse>
	<verse nr="13">
		<slav>
			<num>Gi</num> Пощади1тъ ни1ща и3 ўб0га, и3 дyшы ўб0гихъ спасeтъ:</slav>
		<rus>Будет милосерд к нищему и убогому, и души убогих спасет;</rus>
	</verse>
	<verse nr="14">
		<slav>
			<num>д7i</num> t ли1хвы  и3 t непрaвды и3збaвитъ дyшы и4хъ, и3 чeстно и4мz є3гw2 пред8 ни1ми.</slav>
		<rus>от коварства и насилия избавит души их, и драгоценна будет кровь их пред очами его;</rus>
	</verse>
	<verse nr="15">
		<slav>
			<num>є7i</num> И# жи1въ бyдетъ, и3 дaстсz є3мY t злaта ґравjйска: и3 пом0лzтсz њ нeмъ вhну, вeсь дeнь благословsтъ є3го2.</slav>
		<rus>и будет жить, и будут давать ему от золота Аравии, и будут молиться о нем непрестанно, всякий день благословлять его;</rus>
	</verse>
	<verse nr="16">
		<slav>
			<num>ѕ7i</num> Бyдетъ ўтверждeніе на земли2 на версёхъ г0ръ: превознесeтсz пaче лівaна пл0дъ є3гw2, и3 процвэтyтъ t грaда ћкw травA земнaz.</slav>
		<rus>будет обилие хлеба на земле, наверху гор; плоды его будут волноваться, как лес на Ливане, и в городах размножатся люди, как трава на земле;</rus>
	</verse>
	<verse nr="17">
		<slav>
			<num>з7i</num> Бyдетъ и4мz є3гw2 благословeно во вёки, прeжде с0лнца пребывaетъ и4мz є3гw2: и3 благословsтсz въ нeмъ вс‰ кwлёна земнaz, вси2 kзhцы ўблажaтъ є3го2.</slav>
		<rus>будет имя его [благословенно] вовек; доколе пребывает солнце, будет передаваться имя его; и благословятся в нем [все племена земные], все народы ублажат его.</rus>
	</verse>
	<verse nr="18">
		<slav>
			<num>}i</num> Блгcвeн гDь бGъ ї}левъ, творsй чудесA є3ди1нъ,</slav>
		<rus>Благословен Господь Бог, Бог Израилев, един творящий чудеса,</rus>
	</verse>
	<verse nr="19">
		<slav>
			<num>f7i</num> и3 блгcвeно и4мz слaвы є3гw2 во вёкъ и3 въ вёкъ вёка: и3 и3сп0лнитсz слaвы є3гw2 всS землS: бyди, бyди.</slav>
		<rus>и благословенно имя славы Его вовек, и наполнится славою Его вся земля. Аминь и аминь.</rus>
	</verse>
</psalm>

=== alakim/slavbible/trunk/psalter/src/ps_139.xml
<?xml version="1.0" encoding="Windows-1251"?>
<!DOCTYPE psalm SYSTEM "psalm.dtd">
<?xml-stylesheet type="text/xsl" href="Page.xsl"?>
<psalm nr="139">
	<title>Въ конeцъ, pал0мъ дв7ду, <num>рlf</num>.</title>
	<verse nr="1">
		<slav>
			<initial>И#</initial>зми1 мz, гDи, t человёка лукaва, t мyжа непрaведна и3збaви мS:</slav>
		<rus>Избавь меня, Господи, от человека злого; сохрани меня от притеснителя:</rus>
	</verse>
	<verse nr="2">
		<slav>
			<num>в7</num> иже помhслиша непрaвду въ сeрдцы, вeсь дeнь њполчaху бр†ни:</slav>
		<rus>они злое мыслят в сердце, всякий день ополчаются на брань,</rus>
	</verse>
	<verse nr="3">
		<slav>
			<num>G</num> и3з8wстри1ша z3зhкъ св0й ћкw ѕміи1нъ: ћдъ ѓспідовъ под8 ўстнaми и4хъ. </slav>
		<rus>изощряют язык свой, как змея; яд аспида под устами их.</rus>
	</verse>
	<verse nr="4">
		<slav>
			<num>д7</num> Сохрани1 мz, гDи, и3з8 руки2 грёшничи, t человBкъ непрaведныхъ и3зми1 мz, и5же помhслиша запsти стwпы2 мо‰.</slav>
		<rus>Соблюди меня, Господи, от рук нечестивого, сохрани меня от притеснителей, которые замыслили поколебать стопы мои.</rus>
	</verse>
	<verse nr="5">
		<slav>
			<num>є7</num> Скрhша г0рдіи сёть мнЁ и3 ќжы, препsша сёть ногaма мои1ма:</slav>
		<rus>Гордые скрыли силки для меня и петли, раскинули сеть по дороге, тенета разложили для меня.</rus>
	</verse>
	<verse nr="6">
		<slav>
			<num>ѕ7</num> при стези2 соблaзны положи1ша ми2.</slav>
		<rus>Я сказал Господу: Ты Бог мой; услышь, Господи, голос молений моих!</rus>
	</verse>
	<verse nr="7">
		<slav>
			<num>з7</num> Рёхъ гDеви: бGъ м0й є3си2 ты2, внуши2, гDи, глaсъ молeніz моегw2.</slav>
		<rus>Господи, Господи, сила спасения моего! Ты покрыл голову мою в день брани.</rus>
	</verse>
	<verse nr="8">
		<slav>
			<num>}</num> ГDи, гDи, си1ло спcніz моегw2, њсэни1лъ є3си2 над8 глав0ю моeю въ дeнь брaни.</slav>
		<rus>Не дай, Господи, желаемого нечестивому; не дай успеха злому замыслу его: они возгордятся.</rus>
	</verse>
	<verse nr="9">
		<slav>
			<num>f7</num> Не предaждь менE, гDи, t желaніz моегw2 грёшнику: помhслиша на мS, не њстaви менE, да не когдA вознесyтсz.</slav>
		<rus>Да покроет головы окружающих меня зло собственных уст их.</rus>
	</verse>
	<verse nr="10">
		<slav>
			<num>‹</num> ГлавA њкружeніz и4хъ, трyдъ ўстeнъ и4хъ покрhетъ |.</slav>
		<rus>Да падут на них горящие угли; да будут они повержены в огонь, в пропасти, так, чтобы не встали.</rus>
	</verse>
	<verse nr="11">
		<slav>
			<num>№i</num> Падyтъ на ни1хъ ќгліz џгнєннаz, низложи1ши | во страстeхъ, и3 не постоsтъ.</slav>
		<rus>Человек злоязычный не утвердится на земле; зло увлечет притеснителя в погибель.</rus>
	</verse>
	<verse nr="12">
		<slav>
			<num>в7i</num> Мyжъ z3зhченъ не и3спрaвитсz на земли2: мyжа непрaведна ѕл†z ўловsтъ во и3стлёніе.</slav>
		<rus>Знаю, что Господь сотворит суд угнетенным и справедливость бедным.</rus>
	</verse>
	<verse nr="13">
		<slav>
			<num>Gi</num> Познaхъ, ћкw сотвори1тъ гDь сyдъ ни1щымъ и3 мeсть ўбHгимъ.</slav>
		<rus>Так! праведные будут славить имя Твое; непорочные будут обитать пред лицем Твоим.</rus>
	</verse>
	<verse nr="14">
		<slav>
			<num>д7i</num> Nбaче првdніи и3сповёдzтсz и4мени твоемY, и3 вселsтсz прaвіи съ лицeмъ твои1мъ.</slav>
		<rus>Так! праведные будут славить имя Твое; непорочные будут обитать пред лицем Твоим.</rus>
	</verse>
</psalm>

=== alakim/slavbible/psalter/src/ps_134.xml
<?xml version="1.0" encoding="Windows-1251"?>
<!DOCTYPE psalm SYSTEM "psalm.dtd">
<?xml-stylesheet type="text/xsl" href="Page.xsl"?>
<psalm nr="134">
	<title>А#ллилyіа, <num>рlд</num>.</title>
	<verse nr="1">
		<slav>
			<initial>Х</initial>вали1те и4мz гDне, хвали1те, раби2 гDа,</slav>
		<rus>Хвалите имя Господне, хвалите, рабы Господни,</rus>
	</verse>
	<verse nr="2">
		<slav>
			<num>в7</num> стоsщіи во хрaмэ гDни, во дв0рэхъ д0му бGа нaшегw.</slav>
		<rus>стоящие в доме Господнем, во дворах дома Бога нашего.</rus>
	</verse>
	<verse nr="3">
		<slav>
			<num>G</num> Хвали1те гDа, ћкw блaгъ гDь: п0йте и4мени є3гw2, ћкw добро2:</slav>
		<rus>Хвалите Господа, ибо Господь благ; пойте имени Его, ибо это сладостно,</rus>
	</verse>
	<verse nr="4">
		<slav>
			<num>д7</num> ћкw їaкwва и3збрA себЁ гDь, ї}лz въ достоsніе себЁ:</slav>
		<rus>ибо Господь избрал Себе Иакова, Израиля в собственность Свою.</rus>
	</verse>
	<verse nr="5">
		<slav>
			<num>є7</num> ћкw ѓзъ познaхъ, ћкw вeлій гDь, и3 гDь нaшъ над8 всёми бHги:</slav>
		<rus>Я познал, что велик Господь, и Господь наш превыше всех богов.</rus>
	</verse>
	<verse nr="6">
		<slav>
			<num>ѕ7</num> вс‰, є3ли6ка восхотЁ гDь, сотвори2 на нб7си2 и3 на земли2, въ морsхъ и3 во всёхъ бeзднахъ.</slav>
		<rus>Господь творит все, что хочет, на небесах и на земле, на морях и во всех безднах;</rus>
	</verse>
	<verse nr="7">
		<slav>
			<num>з7</num> ВозводS w4блаки t послёднихъ земли2, мHлніи въ д0ждь сотвори2, и3зводsй вётры t сокр0вищъ свои1хъ.</slav>
		<rus>возводит облака от края земли, творит молнии при дожде, изводит ветер из хранилищ Своих.</rus>
	</verse>
	<verse nr="8">
		<slav>
			<num>}</num> И$же порази2 пeрвенцы є3гЂпєтскіz t человёка до скотA:</slav>
		<rus>Он поразил первенцев Египта, от человека до скота,</rus>
	</verse>
	<verse nr="9">
		<slav>
			<num>f7</num> послA знaмєніz и3 чудесA посредЁ тебє2, є3гЂпте, на фараHна и3 на вс‰ рабы6 є3гw2.</slav>
		<rus>послал знамения и чудеса среди тебя, Египет, на фараона и на всех рабов его,</rus>
	</verse>
	<verse nr="10">
		<slav>
			<num>‹</num> И$же порази2 kзhки мнHги и3 и3зби2 цари6 крBпки:</slav>
		<rus>поразил народы многие и истребил царей сильных:</rus>
	</verse>
	<verse nr="11">
		<slav>
			<num>№i</num> сиHна царS ґморрeйска и3 w4га царS васaнска, и3 вс‰ ц†рствіz хана†нска:</slav>
		<rus>Сигона, царя Аморрейского, и Ога, царя Васанского, и все царства Ханаанские;</rus>
	</verse>
	<verse nr="12">
		<slav>
			<num>в7i</num> и3 дадE зeмлю и4хъ достоsніе, достоsніе ї}лю лю1демъ свои6мъ.</slav>
		<rus>и отдал землю их в наследие, в наследие Израилю, народу Своему.</rus>
	</verse>
	<verse nr="13">
		<slav>
			<num>Gi</num> ГDи, и4мz твоE въ вёкъ, и3 пaмzть твоS въ р0дъ и3 р0дъ:</slav>
		<rus>Господи! имя Твое вовек; Господи! память о Тебе в род и род.</rus>
	</verse>
	<verse nr="14">
		<slav>
			<num>д7i</num> ћкw суди1ти и4мать гDь лю1демъ свои6мъ, и3 њ рабёхъ свои1хъ ўм0литсz.</slav>
		<rus>Ибо Господь будет судить народ Свой и над рабами Своими умилосердится.</rus>
	</verse>
	<verse nr="15">
		<slav>
			<num>є7i</num> Јдwли kзы6къ сребро2 и3 злaто, дэлA рyкъ человёческихъ:</slav>
		<rus>Идолы язычников - серебро и золото, дело рук человеческих:</rus>
	</verse>
	<verse nr="16">
		<slav>
			<num>ѕ7i</num> ўстA и4мутъ, и3 не возглаг0лютъ: џчи и4мутъ, и3 не ќзрzтъ:</slav>
		<rus>есть у них уста, но не говорят; есть у них глаза, но не видят;</rus>
	</verse>
	<verse nr="17">
		<slav>
			<num>з7i</num> ќши и4мутъ, и3 не ўслhшатъ: нижe бо є4сть дyхъ во ўстёхъ и4хъ.</slav>
		<rus>есть у них уши, но не слышат, и нет дыхания в устах их.</rus>
	</verse>
	<verse nr="18">
		<slav>
			<num>}i</num> Под0бни и5мъ да бyдутъ творsщіи | и3 вси2 надёющіисz на нS.</slav>
		<rus>Подобны им будут делающие их и всякий, кто надеется на них.</rus>
	</verse>
	<verse nr="19">
		<slav>
			<num>f7i</num> Д0ме ї}левъ, благослови1те гDа: д0ме ґарHнь, благослови1те гDа: д0ме леvjинъ, благослови1те гDа:</slav>
		<rus>Дом Израилев! благословите Господа. Дом Ааронов! благословите Господа.</rus>
	</verse>
	<verse nr="20">
		<slav>
			<num>к7</num> боsщіисz гDа, благослови1те гDа.</slav>
		<rus>Дом Левиин! благословите Господа. Боящиеся Господа! благословите Господа.</rus>
	</verse>
	<verse nr="21">
		<slav>
			<num>к7а</num> Блгcвeнъ гDь t сіHна, живhй во їерcли1мэ.</slav>
		<rus>Благословен Господь от Сиона, живущий в Иерусалиме! Аллилуия!</rus>
	</verse>
</psalm>
